// Generated by design-token-bridge-mcp
// MiLens 设计 token — SwiftUI 参考映射（Light）
// 注意：这是设计 token 的参考实现，非 App 实际使用的 Color+Theme.swift。
// 实际工程中颜色走 Asset Catalog colorset + Color.milensXxx 语义命名（见 Theme/Color+Theme.swift），
// 此处用 Color(red:green:blue:) 仅为可读参考，不应引入编译源（项目 lint 禁止硬编码 RGB）。
// 深色外观请在 Asset Catalog 中对应 colorset 的 Dark 变体维护，值见 UI-DESIGN.md §3.1。

import SwiftUI

// MARK: - Colors

extension Color {
    static let canvas = Color(red: 0.980, green: 0.973, blue: 0.961)             // #FAF8F5
    static let surface = Color(red: 1.000, green: 1.000, blue: 1.000)             // #FFFFFF
    static let surfaceSecondary = Color(red: 0.949, green: 0.937, blue: 0.918)     // #F2EFEA
    static let surfaceElevated = Color(red: 1.000, green: 1.000, blue: 1.000)      // #FFFFFF
    static let textPrimary = Color(red: 0.122, green: 0.106, blue: 0.094)          // #1F1B18
    static let textSecondary = Color(red: 0.420, green: 0.384, blue: 0.357)        // #6B625B
    static let textMuted = Color(red: 0.467, green: 0.427, blue: 0.396)            // #776D65
    static let brandCoral = Color(red: 0.992, green: 0.525, blue: 0.388)           // #FD8663
    static let actionPrimary = Color(red: 0.737, green: 0.278, blue: 0.153)        // #BC4727
    static let onActionPrimary = Color(red: 1.000, green: 1.000, blue: 1.000)      // #FFFFFF
    static let accentSoft = Color(red: 0.988, green: 0.910, blue: 0.875)           // #FCE8DF
    static let borderSubtle = Color(red: 0.898, green: 0.875, blue: 0.847)         // #E5DFD8
    static let separator = Color(red: 0.925, green: 0.906, blue: 0.882)            // #ECE7E1
    static let success = Color(red: 0.184, green: 0.490, blue: 0.341)              // #2F7D57
    static let warning = Color(red: 0.604, green: 0.357, blue: 0.000)              // #9A5B00
    static let danger = Color(red: 0.702, green: 0.227, blue: 0.212)               // #B33A36
}
