# -*- coding: utf-8 -*-
"""English translation dictionary - Part 5B (303 keys)."""

P5B_EN = {
    "editor.adjust.exposure": "Exposure",
    "editor.adjust.highlights": "Highlights",
    "editor.adjust.shadows": "Shadows",
    "editor.adjust.temperature": "Color Temperature",
    "editor.adjust.tint": "Tint",
    "editor.adjust.vibrance": "Vibrance",
    "editor.crop.rotateFree": "Free Rotate",
    "editor.crop.straighten": "Straighten",
    "editor.cutout.auto": "Smart Auto Cutout",
    "editor.cutout.brushSize": "Brush Size",
    "editor.cutout.clear": "Clear Selection",
    "editor.cutout.edgeSmooth": "Smooth Edges",
    "editor.cutout.erase": "Erase",
    "editor.cutout.manual": "Manual Brush",
    "editor.cutout.paint": "Paint",
    "editor.cutout.preview": "Cutout Preview",
    "editor.cutout.refine": "Refine Cutout",
    "editor.cutout.restore": "Restore",
    "editor.cutout.undo": "Undo Cutout Step",
    "editor.filter.category.film": "Vintage Film",
    "editor.filter.category.monochrome": "B&W",
    "editor.filter.category.natural": "Natural Tones",
    "editor.filter.category.portrait": "Pal Portrait",
    "editor.filter.intensity": "Filter Intensity",
    "editor.filter.reset": "Original (No Filter)",
    "editor.layer.bringForward": "Bring Forward",
    "editor.layer.bringToFront": "Bring to Front",
    "editor.layer.delete": "Delete Layer",
    "editor.layer.duplicate": "Duplicate Layer",
    "editor.layer.lock": "Lock Layer",
    "editor.layer.opacity": "Opacity",
    "editor.layer.sendBackward": "Send Backward",
    "editor.layer.sendToBack": "Send to Back",
    "editor.layer.unlock": "Unlock Layer",
    "editor.text.backgroundColor": "Background Color",
    "editor.text.spacing": "Character Spacing",
    "decoration.sticker.more": "More Stickers",
    "decoration.sticker.recent": "Recently Used",
    "decoration.sticker.search": "Search Stickers",
    "decoration.frame.custom": "Custom Frame",
    "decoration.frame.more": "More Frames",
    "decoration.frame.shadow": "Frame Shadow",
    "decoration.frame.width": "Border Width",
    "decoration.textStyle.gradient": "Gradient",
    "businesscard.design.cardStyle": "Card Style",
    "businesscard.design.front": "Front Side",
    "businesscard.design.back": "Back Side",
    "businesscard.design.layout": "Layout",
    "businesscard.design.qrCode": "QR Code",
    "businesscard.design.signature": "Paw Signature",
    "businesscard.design.stamp": "Official Seal",
    "businesscard.export.frontBack": "Export Both Sides",
    "businesscard.export.highRes": "High-Res PNG",
    "businesscard.export.pdfPrint": "Printable PDF",
    "businesscard.style.modern": "Modern Clean",
    "businesscard.style.retro": "Vintage Classic",
    "businesscard.style.sweet": "Sweet Pastel",
    "businesscard.theme.gold": "Golden Leaf",
    "businesscard.theme.navy": "Midnight Navy",
    "businesscard.theme.rose": "Blush Rose",
    "businessCard.exportSuccess": "Pal card saved to Photos",
    "businessCard.flipCard": "Flip Card",
    "businessCard.preview": "Card Preview",
    "businessCard.title": "Pal ID Card",
    "album.candidates.badge": "Candidates",
    "album.candidates.confirmAll": "Confirm All",
    "album.candidates.dismiss": "Dismiss",
    "album.candidates.filter": "Filter Candidates",
    "album.candidates.footer": "AI discovered photos that may match your pal. Confirm to import into their archive.",
    "album.candidates.heading": "Candidate Photo Review",
    "album.candidates.help": "Why are photos grouped here?",
    "album.candidates.ignore": "Not My Pal",
    "album.candidates.manage": "Manage Candidates",
    "album.candidates.noMatch": "No matching pal found",
    "album.candidates.progress": "Reviewing photos...",
    "album.candidates.selectTarget": "Assign to Pal",
    "album.candidates.skip": "Skip for Now",
    "album.group.byDate": "Group by Date",
    "album.group.byMonth": "Group by Month",
    "album.group.byPal": "Group by Pal",
    "album.group.byYear": "Group by Year",
    "album.petSelect.all": "All Pals",
    "album.petSelect.cancel": "Cancel",
    "album.petSelect.done": "Done",
    "album.petSelect.empty": "No pal profiles created yet",
    "album.petSelect.footer": "Photos will be organized under the selected pal's growth timeline.",
    "album.petSelect.header": "Select Pal Profile",
    "album.petSelect.newPal": "Create New Pal Profile",
    "album.petSelect.select": "Select",
    "album.scan.autoScan": "Auto Background Scan",
    "album.scan.deepScan": "Deep Scan Library",
    "album.scan.footer": "Scanning runs entirely on device and only processes photos within your authorized scope.",
    "album.scan.lastScan": "Last scanned",
    "album.scan.paused": "Scan Paused",
    "album.scan.rescan": "Rescan Library",
    "gallery.action.addToPal": "Assign to Pal",
    "gallery.action.filter": "Filter",
    "gallery.action.multiSelect": "Select",
    "gallery.action.sort": "Sort",
    "gallery.dateRange.all": "All Time",
    "gallery.dateRange.month": "This Month",
    "gallery.dateRange.week": "Past 7 Days",
    "gallery.dateRange.year": "This Year",
    "gallery.empty.importCTA": "Import Photos Now",
    "gallery.empty.scanCTA": "Scan Library for Pals",
    "gallery.selection.count %lld": "%lld Selected",
    "gallery.selection.delete": "Delete Selected",
    "gallery.selection.share": "Share Selected",
    "picker.action.back": "Back",
    "picker.action.clear": "Clear",
    "picker.action.preview": "Preview",
    "picker.count.selected %lld": "%lld Selected",
    "picker.empty.noPhotos": "No photos found",
    "picker.filter.favorites": "Favorites",
    "picker.filter.recents": "Recents",
    "picker.filter.screenshots": "Screenshots",
    "picker.filter.videos": "Videos",
    "picker.header.all": "All Photos",
    "picker.header.pals": "Pal Photos",
    "picker.limit.notice": "Selection Limit",
    "picker.nav.done": "Done",
    "picker.permission.denied": "Photo Library Access Denied",
    "picker.permission.hint": "Please enable photo permissions in Settings to pick photos.",
    "picker.permission.openSettings": "Open Settings",
    "picker.prompt.choose": "Select photos of your pal",
    "picker.prompt.max": "Maximum selection reached",
    "picker.prompt.min": "Please select at least one photo",
    "picker.search.placeholder": "Search by date or album...",
    "picker.selected.badge %lld": "%lld",
    "picker.tab.albums": "Albums",
    "picker.tab.photos": "Photos",
    "photo.action.bead": "Make Bead Art",
    "photo.action.card": "Make Pal Card",
    "photo.action.copy": "Copy Photo",
    "photo.action.deleteRecord": "Delete Record",
    "photo.action.favorite": "Add to Favorites",
    "photo.action.redpacket": "Make Red Packet",
    "photo.action.removeFavorite": "Remove from Favorites",
    "photo.action.reassignPal": "Change Pal",
    "photo.action.saveToLibrary": "Save to System Library",
    "photo.action.share": "Share Photo",
    "photo.detail.dateCaptured": "Date Captured",
    "photo.detail.dimensions": "Dimensions",
    "photo.detail.fileSize": "File Size",
    "photo.detail.location": "Location",
    "photo.detail.noLocation": "No Location Info",
    "photo.detail.palName %@": "%@",
    "photo.detail.qualityScore %lld": "Quality %lld",
    "photo.detail.source": "Source",
    "photo.duplicate.action.keepAll": "Keep All",
    "photo.duplicate.action.keepBest": "Keep Highest Quality",
    "paywall.badge.bestValue": "Best Value",
    "paywall.badge.popular": "Most Popular",
    "paywall.benefit.exportHd": "High-Definition Artwork Export",
    "paywall.benefit.unlimitedBead": "Unlimited Bead Pattern Creation",
    "paywall.benefit.unlimitedPals": "Manage up to 20 Pal Profiles",
    "paywall.benefit.unlimitedPhotos": "Unlimited Pal Photo Storage",
    "paywall.benefit.unlimitedTimeline": "Full Lifetime Growth Timeline",
    "paywall.benefit.watermarkRemoval": "Remove All Watermarks",
    "paywall.cta.monthly": "Monthly Plan",
    "paywall.cta.yearly": "Yearly Plan",
    "paywall.cta.lifetime": "Lifetime Access",
    "paywall.footer.autoRenew": "Subscription auto-renews. Cancel anytime in Apple ID settings.",
    "paywall.footer.familySharing": "Eligible for Apple Family Sharing",
    "paywall.header.pro": "MiLens Pro",
    "paywall.header.subtitle": "Unlock everything for your pal's archive",
    "paywall.plan.savePercent %lld": "Save %lld%%",
    "home.card.anniversaries": "Upcoming Anniversaries",
    "home.card.dailyPick": "Daily Pick",
    "home.card.recentMoments": "Recent Moments",
    "home.card.timeMachine": "This Day in Past Years",
    "home.hero.daysTogether": "Days Together",
    "home.hero.noPal": "Add your first pal to get started",
    "home.hero.tapToView": "Tap to view profile",
    "home.quick.addPhoto": "Add Photo",
    "home.quick.beadStudio": "Bead Studio",
    "home.quick.palCard": "Pal Card",
    "home.quick.scanLibrary": "Scan Library",
    "home.quick.timelinePoster": "Timeline Poster",
    "home.section.anniversary": "Anniversary Countdown",
    "home.section.highlights": "Highlights",
    "home.section.todayInHistory": "Today in Past Years",
    "home.stats.memories": "Memories",
    "home.stats.photos": "Photos",
    "home.stats.works": "Artworks",
    "home.welcome.body": "Your pal's digital life archive starts here.",
    "home.welcome.cta": "Create Pal Profile",
    "home.welcome.title": "Welcome to MiLens",
    "memory.action.pin": "Pin to Top",
    "memory.action.unpin": "Unpin",
    "memory.card.pal %@": "Pal: %@",
    "memory.detail.title": "Memory Details",
    "memory.empty.desc": "Pin your favorite photos and stories to feature them here.",
    "memory.header.pinned": "Pinned Highlights",
    "memory.header.recent": "Recent Flashbacks",
    "memory.list.title": "Memories",
    "memory.manage.pinned": "Manage Pinned Memories",
    "memory.pinned.full": "Maximum 6 pinned memories reached",
    "memory.pinned.maxHint": "Unpin an existing memory to add a new one",
    "memory.pinned.success": "Memory pinned to top",
    "memory.unpinned.success": "Memory unpinned",
    "reminders.empty.body": "Add birthdays, adoption days, and milestones with your pal.",
    "reminders.empty.hint": "Reminders will alert you at 9:00 AM on the day of the event.",
    "reminders.loadError": "Failed to load reminders",
    "reminders.section.memories": "Past Flashbacks",
    "reminders.section.today": "Today's Reminders",
    "reminders.section.upcoming": "Upcoming Anniversaries",
    "reminders.today.adoption %@": "%@'s Adoption Day Today! 🎉",
    "reminders.today.birthday %@": "Happy Birthday to %@! 🎂",
    "reminders.today.memory %lld": "Memories from %lld years ago today",
    "reminders.today.milestone %@ %lld": "%1$@ has been with you for %2$lld days!",
    "reminders.upcoming.dayUnit": "days",
    "reminders.upcoming.daysLeft %lld": "In %lld days",
    "reminders.upcoming.today": "Today!",
    "bell.action.clearAll": "Clear All",
    "bell.action.markRead": "Mark as Read",
    "bell.badge.new": "NEW",
    "bell.empty.desc": "Anniversary alerts and memory flashbacks will appear here.",
    "bell.section.earlier": "Earlier",
    "bell.section.thisWeek": "This Week",
    "bell.section.today": "Today",
    "bell.settings.button": "Notification Settings",
    "bell.subtitle": "Anniversary & Memory Alerts",
    "recap.action.export": "Export Recap Video/Image",
    "recap.action.share": "Share Life Review",
    "recap.cover.title %lld": "Life Review · %lld",
    "recap.header.summary": "Year in Summary",
    "recap.section.growth": "Growth Highlights",
    "recap.section.moments": "Precious Moments",
    "recap.stats.daysTogether %lld": "%lld Days Together",
    "a11y.action.close": "Close button",
    "a11y.action.delete": "Delete button",
    "a11y.action.edit": "Edit button",
    "a11y.action.more": "More options button",
    "a11y.action.save": "Save button",
    "a11y.action.share": "Share button",
    "a11y.card.pal": "Pal card preview",
    "a11y.crop.overlay": "Crop overlay area",
    "a11y.editor.canvas": "Photo editing canvas",
    "a11y.editor.filterItem %@": "Filter %@",
    "a11y.editor.stickerItem %@": "Sticker %@",
    "a11y.gallery.grid": "Photo gallery grid",
    "a11y.gallery.item %@": "Photo %@ in gallery",
    "a11y.memory.pinnedItem": "Pinned memory card",
    "a11y.nav.back": "Back button",
    "a11y.pet.avatarImage %@": "%@'s avatar",
    "a11y.pet.profileCard %@": "%@'s profile card",
    "a11y.picker.photoThumb %@": "Photo captured on %@",
    "a11y.scan.progressBar %lld": "Scan progress %lld percent",
    "a11y.timeline.chapter %@": "Timeline chapter %@",
    "a11y.timeline.milestone %@": "Milestone %@",
    "a11y.timeline.photoCard %@": "Timeline photo %@",
    "a11y.widget.preview": "Widget preview",
    "a11y.zoom.beadBoard": "Bead pegboard canvas",
    "a11y.zoom.hint": "Double tap to zoom in",
    "recovery.action.cancel": "Cancel",
    "recovery.action.diagnose": "Diagnose Database",
    "recovery.action.export": "Export Raw Data",
    "recovery.action.rebuild": "Rebuild Database",
    "recovery.card.body": "Database recovery tool for corrupted local files.",
    "recovery.card.title": "Database Recovery",
    "recovery.heading": "Data Integrity Tool",
    "recovery.step.01": "Check database schema",
    "recovery.step.02": "Verify photo sandbox copies",
    "recovery.step.03": "Repair index and rebuild metadata",
    "recovery.step.04": "Complete recovery",
    "field.adoption": "Adoption Date",
    "field.anniversary": "Anniversary",
    "field.breedName": "Breed",
    "field.description": "Description",
    "field.memorialDate": "Memorial Date",
    "field.palName": "Pal Name",
    "field.profilePhoto": "Profile Photo",
    "field.tag": "Tag",
    "archive.subtitle": "Digital Life Archive",
    "preview.close": "Close Preview"
}
