# -*- coding: utf-8 -*-
"""English translation dictionary - Part 2 (M05 - M08)."""

# M05: Settings, Privacy, Recovery & About (106)
SETTINGS_EN = {
    "about.fonts.note": "All fonts are licensed under the SIL Open Font License 1.1; license texts are bundled with the app.",
    "about.fonts.title": "Fonts & Open Source Licenses",
    "privacy.commit.control": "You decide what gets imported",
    "privacy.commit.control.detail": "Scanning only discovers candidate photos; you confirm what gets imported and which pal it belongs to.",
    "privacy.commit.local": "Analysis happens on your device",
    "privacy.commit.local.detail": "Pal photo recognition runs entirely on local models — no servers involved.",
    "privacy.commit.ondevice": "Photos are never uploaded",
    "privacy.commit.ondevice.detail": "The app never uploads your photos; edited works may be saved by system backups you have enabled.",
    "privacy.commit.title": "On-Device Privacy Promise",
    "privacy.permissions.manage": "Manage photo & notification permissions",
    "privacy.policy.link": "View Privacy Policy",
    "privacy.storage.detail": "Imported photo copies and profile data are stored in the app sandbox. Deleting the app removes this data; originals in your system photo library are unaffected.",
    "privacy.storage.title": "Data Storage",
    "recovery.back": "Back",
    "recovery.body": "There was a problem opening local records. You can retry, or rebuild local data: this clears MiLens records and sandbox photo copies. Originals in your system library are unaffected.",
    "recovery.clearRebuild": "Rebuild Local Data",
    "recovery.clearing": "Clearing...",
    "recovery.rebuild.action": "Clear and Rebuild",
    "recovery.rebuild.message": "This will clear album records, pal profiles, and sandbox photo copies in MiLens. Originals in your system photo library will not be deleted.",
    "recovery.rebuild.title": "Rebuild Local Data",
    "recovery.rebuildConfirmBody": "This will clear album records, pal profiles, and sandbox photo copies in MiLens. This action cannot be undone. Originals in your system photo library are unaffected.",
    "recovery.retry": "Retry",
    "recovery.retryFailed": "Retry failed. You may need to rebuild local data.",
    "recovery.title": "Can't Load Local Data",
    "settings.about.appDesc": "Digital Life Archive for Pal Families",
    "settings.about.appName": "MiLens",
    "settings.about.contact": "Contact Us",
    "settings.about.copyright": "© 2026 Miovelle. All rights reserved.",
    "settings.about.entry": "About MiLens",
    "settings.about.feedback": "Feedback & Support",
    "settings.about.title": "About",
    "settings.about.version": "Version",
    "settings.appearance.dark": "Dark",
    "settings.appearance.light": "Light",
    "settings.appearance.system": "System",
    "settings.appearance.title": "Appearance",
    "settings.backup.export": "Export Backup",
    "settings.backup.export.failed": "Backup export failed",
    "settings.backup.export.footer": "Export all pal profiles, photo records, and timeline data as an offline backup file.",
    "settings.backup.export.success": "Backup exported successfully",
    "settings.backup.exporting": "Exporting backup...",
    "settings.backup.import": "Restore Backup",
    "settings.backup.import.confirm.message": "Restoring will merge or replace current data with the backup file. Proceed?",
    "settings.backup.import.confirm.title": "Restore Backup",
    "settings.backup.import.failed": "Backup restore failed",
    "settings.backup.import.footer": "Restore data from a previously exported MiLens backup file.",
    "settings.backup.import.success": "Backup restored successfully",
    "settings.backup.importing": "Restoring backup...",
    "settings.backup.lastDate %@": "Last backup: %@",
    "settings.backup.never": "Never backed up",
    "settings.backup.title": "Backup & Restore",
    "settings.clearCache": "Clear Cache",
    "settings.clearCache.confirm": "Clear temporary cache files? Archived photos won't be affected.",
    "settings.clearCache.done": "Cache cleared",
    "settings.notifications.anniversary": "Anniversary Reminders",
    "settings.notifications.anniversary.subtitle": "Reminders at 9:00 AM on birthdays and adoption anniversaries",
    "settings.notifications.denied.message": "Please enable notifications for MiLens in System Settings to receive anniversary reminders.",
    "settings.notifications.denied.ok": "OK",
    "settings.notifications.denied.title": "Notifications Disabled",
    "settings.notifications.footer": "When enabled: reminders at 9:00 AM on birthdays and adoption anniversaries; daily 9:00 AM Time Machine memories when photos exist from this day in past years.",
    "settings.notifications.reminders": "Memorial Reminders",
    "settings.notifications.timeMachine": "Time Machine Memories",
    "settings.notifications.timeMachine.subtitle": "Daily 9:00 AM flashback when memories exist from past years",
    "settings.notifications.title": "Notifications",
    "settings.privacy.dataTitle": "On-Device Data",
    "settings.privacy.local": "Local Data & Privacy",
    "settings.privacy.policy": "Privacy Policy",
    "settings.privacy.terms": "Terms of Service",
    "settings.privacy.title": "Privacy & Data",
    "settings.pro.active.manage": "Manage Subscription",
    "settings.pro.active.subtitle": "Unlimited bead patterns, 20 pal profiles & full timeline",
    "settings.pro.active.title": "MiLens Pro Active",
    "settings.pro.banner.badge": "PRO",
    "settings.pro.banner.subtitle": "Unlock unlimited bead patterns & lifetime timeline",
    "settings.pro.banner.title": "Upgrade to MiLens Pro",
    "settings.pro.manage": "Manage Subscription",
    "settings.pro.status.lifetime": "Lifetime Pro",
    "settings.pro.status.monthly": "Monthly Subscription",
    "settings.pro.status.yearly": "Yearly Subscription",
    "settings.pro.title": "MiLens Pro",
    "settings.pro.unlock.subtitle": "Unlock full Bead Studio & photo editor",
    "settings.pro.unlock.title": "Unlock MiLens Pro",
    "settings.rebuild.footer": "If local data is corrupted, you can rebuild the database. Original photos in your system library are safe.",
    "settings.rebuild.title": "Database Rebuild",
    "settings.section.about": "About",
    "settings.section.appearance": "Appearance",
    "settings.section.backup": "Backup & Storage",
    "settings.section.general": "General",
    "settings.section.notifications": "Notifications",
    "settings.section.pals": "Pals",
    "settings.section.privacy": "Data & Privacy",
    "settings.section.pro": "MiLens Pro",
    "settings.section.support": "Support",
    "settings.storage.archivedPhotos %lld": "%lld archived photos",
    "settings.storage.cacheSize %@": "Cache size: %@",
    "settings.storage.count %lld %lld": "%1$lld/%2$lld photos",
    "settings.storage.freeUsage %lld %lld": "Free: %1$lld/%2$lld photos",
    "settings.storage.proUnlimited": "Pro: Unlimited photos",
    "settings.storage.title": "Photo Storage",
    "settings.storage.usage": "Storage Usage",
    "settings.support.feedback": "Feedback",
    "settings.support.help": "Help & FAQ",
    "settings.title": "Settings",
    "startup.unknownError": "An unknown error occurred during launch.",
}

# M06: Red Packet Workshop (186)
REDPACKET_EN = {
    "redpacket.crop.aspectRatio": "Aspect Ratio",
    "redpacket.crop.autoAlign": "Auto Align",
    "redpacket.crop.footer": "Standard WeChat Red Packet Cover ratio is 957 × 1278 (3:4). Keep key subjects within the safe zone.",
    "redpacket.crop.header": "Crop for Red Packet Cover",
    "redpacket.crop.ratio.standard": "WeChat Cover (3:4)",
    "redpacket.crop.reset": "Reset Crop",
    "redpacket.crop.rotate": "Rotate",
    "redpacket.crop.safeArea.hint": "Safe Zone: Avoid important content near the top and bottom edges",
    "redpacket.crop.title": "Crop & Position",
    "redpacket.custom.title": "Custom Cover",
    "redpacket.draft.delete.confirm": "Delete this cover draft?",
    "redpacket.draft.empty.subtitle": "Make a unique WeChat red packet cover with photos of your pal",
    "redpacket.draft.empty.title": "No Drafts Yet",
    "redpacket.draft.lastModified %@": "Edited %@",
    "redpacket.draft.list.title": "My Cover Drafts",
    "redpacket.draft.new": "Create New Cover",
    "redpacket.draft.saved": "Draft saved",
    "redpacket.export.button": "Export Cover Image",
    "redpacket.export.footer": "Exported cover image meets official WeChat Red Packet Cover specifications (PNG, 957 × 1278, < 500 KB).",
    "redpacket.export.format": "Format: PNG (< 500 KB)",
    "redpacket.export.generating": "Exporting cover...",
    "redpacket.export.hd": "HD Export (Pro)",
    "redpacket.export.resolution": "Resolution: 957 × 1278",
    "redpacket.export.saveFailed": "Failed to save cover image",
    "redpacket.export.saveSuccess": "Cover saved to Photos",
    "redpacket.export.sceneOverline": "SCENE PREVIEW",
    "redpacket.export.standard": "Standard Export",
    "redpacket.export.title": "Export WeChat Cover",
    "redpacket.filter.all": "All",
    "redpacket.filter.festive": "Festive",
    "redpacket.filter.minimal": "Minimal",
    "redpacket.filter.vintage": "Vintage",
    "redpacket.filter.warm": "Warm",
    "redpacket.history.title": "Creation History",
    "redpacket.material.avatar": "Pal Avatar",
    "redpacket.material.cutout": "Pal Cutout",
    "redpacket.material.photo": "Full Photo",
    "redpacket.material.select": "Select Material",
    "redpacket.material.title": "Material Type",
    "redpacket.nav.workshop": "Cover Workshop",
    "redpacket.overline": "WECHAT RED ENVELOPES",
    "redpacket.picker.fromAlbum": "Pick from Album",
    "redpacket.picker.fromPal": "Pick from Pal Profile",
    "redpacket.picker.title": "Select Photo for Cover",
    "redpacket.preview.bubble": "Chat Bubble",
    "redpacket.preview.cover": "Cover Page",
    "redpacket.preview.details": "Details Page",
    "redpacket.preview.open": "Open State",
    "redpacket.preview.receiver": "Receiver View",
    "redpacket.preview.scene.bubble": "Chat Message Bubble",
    "redpacket.preview.scene.cover": "Envelope Opening Page",
    "redpacket.preview.scene.details": "Packet Details & Amount",
    "redpacket.preview.scene.open": "Opened Pocket View",
    "redpacket.preview.scene.story": "Cover Story Page",
    "redpacket.preview.sender": "Sender View",
    "redpacket.preview.story": "Story",
    "redpacket.preview.switchScene": "Switch Scene",
    "redpacket.preview.title": "WeChat Scene Preview",
    "redpacket.quality.badge.excellent": "Excellent",
    "redpacket.quality.badge.fair": "Fair",
    "redpacket.quality.badge.good": "Good",
    "redpacket.quality.badge.poor": "Needs Improvement",
    "redpacket.quality.clarity": "Clarity",
    "redpacket.quality.clarity.detail": "Sharpness & resolution of pal subject",
    "redpacket.quality.composition": "Composition",
    "redpacket.quality.composition.detail": "Subject centered within safe zone",
    "redpacket.quality.contrast": "Contrast & Lighting",
    "redpacket.quality.contrast.detail": "Clear separation from background",
    "redpacket.quality.detail.clarity.high": "High sharpness — pal subject is crisp and clear",
    "redpacket.quality.detail.clarity.low": "Image is slightly blurry — recommend higher resolution photo",
    "redpacket.quality.detail.clarity.med": "Good sharpness — suitable for red packet display",
    "redpacket.quality.detail.composition.bad": "Subject is too close to edge — may be clipped by WeChat UI",
    "redpacket.quality.detail.composition.good": "Subject is well centered within the safe area",
    "redpacket.quality.detail.contrast.bad": "Low contrast with background — subject may blend in",
    "redpacket.quality.detail.contrast.good": "High contrast — subject stands out clearly",
    "redpacket.quality.detail.mask.bad": "Subject overlaps with WeChat button or text area",
    "redpacket.quality.detail.mask.good": "Clear of interactive buttons and title areas",
    "redpacket.quality.footer": "Quality score evaluates clarity, composition, and safe zone compliance according to WeChat official guidelines.",
    "redpacket.quality.header": "Quality Assessment",
    "redpacket.quality.level.excellent": "Ready for WeChat Submission",
    "redpacket.quality.level.good": "Good Quality",
    "redpacket.quality.level.needsImprovement": "Adjustment Recommended",
    "redpacket.quality.mask": "Safe Area Clearance",
    "redpacket.quality.mask.detail": "Avoids overlap with WeChat open button & avatar",
    "redpacket.quality.overall": "Overall Quality Score",
    "redpacket.quality.overline": "QUALITY",
    "redpacket.quality.score %lld": "Score: %lld / 100",
    "redpacket.quality.suggestion.clarity": "Use an original uncompressed photo for best clarity",
    "redpacket.quality.suggestion.composition": "Adjust crop to position pal subject in the upper-middle area",
    "redpacket.quality.suggestion.contrast": "Adjust brightness and warmth in editor for better vibrancy",
    "redpacket.quality.suggestion.mask": "Keep lower third clear of key elements for the WeChat open button",
    "redpacket.quality.title": "Cover Quality Score",
    "redpacket.rules.banner": "WeChat Red Packet Cover Specifications",
    "redpacket.rules.c1": "Resolution: Exactly 957 × 1278 pixels",
    "redpacket.rules.c2": "Format: PNG or JPG, file size under 500 KB",
    "redpacket.rules.c3": "Safe Zone: Keep main subject centered, away from top & bottom edges",
    "redpacket.rules.c4": "Content: Original photos of your own pal; avoid third-party logos",
    "redpacket.rules.link": "Official WeChat Red Packet Platform",
    "redpacket.rules.title": "Submission Guidelines",
    "redpacket.style.classic": "Festive Red",
    "redpacket.style.gold": "Golden Auspicious",
    "redpacket.style.lantern": "Lantern Glow",
    "redpacket.style.modern": "Modern Minimal",
    "redpacket.style.paw": "Lucky Paw",
    "redpacket.style.spring": "Spring Bloom",
    "redpacket.style.title": "Cover Style Theme",
    "redpacket.style.warm": "Warm Hearth",
    "redpacket.tab.create": "Create",
    "redpacket.tab.drafts": "Drafts",
    "redpacket.tab.preview": "Preview",
    "redpacket.tab.rules": "Guidelines",
    "redpacket.template.chineseNewYear": "Spring Festival",
    "redpacket.template.cute": "Playful Pal",
    "redpacket.template.custom": "Custom Template",
    "redpacket.template.daily": "Daily Greetings",
    "redpacket.template.festive": "Happy Holiday",
    "redpacket.template.lucky": "Good Fortune",
    "redpacket.template.minimal": "Clean Aesthetic",
    "redpacket.template.newYear": "New Year Blessing",
    "redpacket.template.title": "Cover Template",
    "redpacket.tool.adjust": "Adjust",
    "redpacket.tool.crop": "Crop",
    "redpacket.tool.cutout": "Cutout",
    "redpacket.tool.filter": "Filter",
    "redpacket.tool.frame": "Frame",
    "redpacket.tool.sticker": "Sticker",
    "redpacket.tool.text": "Text",
    "redpacket.workshop.body": "Turn photos of your pal into official WeChat Red Packet Covers in a few taps.",
    "redpacket.workshop.cta": "Start Creating",
    "redpacket.workshop.feature.crop": "Smart 957×1278 Cropping",
    "redpacket.workshop.feature.export": "One-Tap Standard PNG Export",
    "redpacket.workshop.feature.preview": "Multi-Scene WeChat Simulation",
    "redpacket.workshop.feature.quality": "Real-Time Quality & Safe Zone Scoring",
    "redpacket.workshop.hero": "Create WeChat Red Packet Cover",
    "redpacket.workshop.subtitle": "Give red packets with your pal's unique charm",
    "redpacket.workshop.title": "Red Packet Cover Workshop",
    "redpacket.workshop.proBadge": "PRO EXCLUSIVE",
}

# M07: Create & Bead Studio (95)
CREATE_BEAD_EN = {
    "bead.board.hexagon": "Hexagon Board",
    "bead.board.round": "Round Board",
    "bead.board.shape": "Board Shape",
    "bead.board.size %lld %lld": "%lld × %lld beads",
    "bead.board.square": "Square Board",
    "bead.board.title": "Pegboard Configuration",
    "bead.export.a4pdf": "A4 Printable PDF",
    "bead.export.hdImage": "High-Definition Image",
    "bead.export.materials": "Materials & Color List",
    "bead.export.preview": "Export Preview",
    "bead.export.proHD": "HD Export (Pro)",
    "bead.export.saveFailed": "Failed to save bead pattern",
    "bead.export.saveSuccess": "Pattern saved to Photos",
    "bead.export.share": "Share Pattern",
    "bead.export.title": "Export Bead Pattern",
    "bead.export.watermarkFree": "Watermark-Free (Pro)",
    "bead.generating.progress %lld": "Generating pattern... %lld%%",
    "bead.generating.step1": "Analyzing pal subject features",
    "bead.generating.step2": "Computing color quantization & pixel grid",
    "bead.generating.step3": "Matching MARD color palette codes",
    "bead.generating.step4": "Rendering pegboard layout & numbers",
    "bead.generating.title": "Creating Bead Pattern",
    "bead.mard.code %@": "MARD %@",
    "bead.mard.colorCount %lld": "%lld Colors",
    "bead.mard.palette": "MARD Standard Palette",
    "bead.mard.title": "MARD Bead Codes",
    "bead.palette.contrast": "High Contrast",
    "bead.palette.monochrome": "Monochrome / Grayscale",
    "bead.palette.natural": "Natural Tones",
    "bead.palette.pastel": "Pastel / Soft",
    "bead.palette.select": "Palette Style",
    "bead.palette.title": "Color Palette",
    "bead.palette.vibrant": "Vibrant / Rich",
    "bead.quota.dailyFree %lld %lld": "Daily free patterns: %1$lld/%2$lld",
    "bead.quota.exceeded": "Daily 5-pattern limit reached. Upgrade to Pro for unlimited creation!",
    "bead.quota.proUnlimited": "Pro: Unlimited Generation",
    "bead.result.boardCount %lld": "%lld Pegboards Required",
    "bead.result.colorCount %lld": "%lld Colors Needed",
    "bead.result.hint": "💡 Zoom in on the pattern to display color codes on beads",
    "bead.result.materials": "Materials List",
    "bead.result.size %@": "Size: %@",
    "bead.result.title": "Bead Pattern Result",
    "bead.result.totalBeads %lld": "%lld Total Beads",
    "create.bead.a4pdf": "Pro · A4 PDF",
    "create.bead.colorCount %lld": "%lld Colors",
    "create.bead.colorTransition": "Color Transition",
    "create.bead.cutoutSubject": "Cut Out Subject Only",
    "create.bead.cutoutSubject.hint": "Auto-cutout pal subject to generate on clean background",
    "create.bead.density": "Detail Level",
    "create.bead.density.high": "High Detail",
    "create.bead.density.low": "Low (Fast)",
    "create.bead.density.med": "Medium",
    "create.bead.generate": "Generate Pattern",
    "create.bead.generating": "Generating Pattern...",
    "create.bead.hdExport": "HD Export",
    "create.bead.maxColors %lld": "Max Colors: %lld",
    "create.bead.palette.custom": "Custom Palette",
    "create.bead.palette.mard": "MARD Standard",
    "create.bead.palette.perler": "Perler Standard",
    "create.bead.palette.title": "Color Card Brand",
    "create.bead.patternSize": "Pattern Size",
    "create.bead.preview": "Real-Time Preview",
    "create.bead.size.large %lld": "Large (%lld×%lld)",
    "create.bead.size.medium %lld": "Medium (%lld×%lld)",
    "create.bead.size.small %lld": "Small (%lld×%lld)",
    "create.bead.style.art": "Pixel Art",
    "create.bead.style.cartoon": "Cartoon Illustration",
    "create.bead.style.photo": "Photo Realistic",
    "create.bead.style.title": "Artwork Style",
    "create.bead.subtitle": "Turn photos of your pal into pixel bead patterns",
    "create.bead.title": "Bead Pattern Studio",
    "create.card.subtitle": "Generate digital pal ID cards with customizable styles",
    "create.card.title": "Pal Card Maker",
    "create.header.title": "Creative Studio",
    "create.redpacket.subtitle": "WeChat Red Packet Covers with 957×1278 standard ratio",
    "create.redpacket.title": "Red Packet Cover",
    "create.studio.body": "Turn precious moments with your pal into bead patterns, personalized cards, and red packet covers.",
    "create.studio.cta": "Pick Photo to Create",
    "create.studio.empty.subtitle": "Select a photo of your pal from your library to begin",
    "create.studio.empty.title": "Ready to Create",
    "create.studio.hero": "Creation Studio",
    "create.studio.overline": "CREATION DARKROOM",
    "create.studio.subtitle": "Craft beautiful keepsakes with photos of your pal",
    "create.studio.title": "Studio",
    "create.timeline.subtitle": "Export long chronological growth memory poster",
    "create.timeline.title": "Timeline Poster",
}

# M08: Paywall & Quota (59)
PAYWALL_QUOTA_EN = {
    "a11y.gallery.lockedPhoto": "Locked photo",
    "paywall.alert.ok": "OK",
    "paywall.alert.title": "Notice",
    "paywall.badge.recommended": "Recommended",
    "paywall.benefit.albumModes": "Vintage album browsing modes",
    "paywall.benefit.beadQuota": "Unlimited bead pattern generation",
    "paywall.benefit.cardTemplates": "Exclusive card templates",
    "paywall.benefit.family": "Supports Apple Family Sharing",
    "paywall.benefit.offlineBackup": "Offline photo backup & restore",
    "paywall.benefit.photoStorage": "Unlimited pal photo storage",
    "paywall.benefit.profiles": "Manage up to 20 pal profiles",
    "paywall.benefit.timeline": "Full growth timeline with past years' stories",
    "paywall.benefit.timelineExport": "Export & share growth timeline posters",
    "paywall.benefit.watermarkFree": "Watermark-free exports",
    "paywall.close": "Close",
    "paywall.cta.lifetime.price": "Unlock Lifetime · %@",
    "paywall.cta.subscribe.price": "Subscribe Now · %@",
    "paywall.cta.unavailable": "Unavailable",
    "paywall.future.body": "Advanced creative templates and HD exports are planned for V1.0 and will unlock automatically for Pro members.",
    "paywall.link.privacy": "Privacy Policy",
    "paywall.link.terms": "Terms of Service",
    "paywall.load.failed": "Unable to load subscription info. Please check your connection and try again.",
    "paywall.period.monthly": "Monthly",
    "paywall.period.once": "One-Time",
    "paywall.period.yearly": "Yearly",
    "paywall.pro.owned": "You've unlocked MiLens Pro",
    "paywall.purchase.failed": "Purchase didn't complete. Please try again later.",
    "paywall.purchase.pending": "Purchase is pending confirmation and will unlock automatically once completed.",
    "paywall.restore": "Restore Purchase",
    "paywall.restore.done": "Your purchases have been restored.",
    "paywall.restore.failed": "Restore failed. Please try again later.",
    "paywall.restore.none": "No purchases found to restore.",
    "paywall.retry": "Retry",
    "paywall.subtitle": "Unlock every creative feature in one go",
    "paywall.terms.lifetime": "Pay once, use forever. No recurring fees.",
    "paywall.terms.subscription": "Renews automatically at %@. Cancel anytime in App Store Account Settings; your current period remains valid after cancellation.",
    "paywall.terms.trial": "Free for %1$d days, then renews at %2$@. Cancel anytime in App Store Account Settings; your current period remains valid after cancellation.",
    "paywall.title": "Turn this photo into a keepsake",
    "photo.batch.delete": "Delete",
    "photo.batch.delete.confirm %lld": "Delete %lld selected photos?",
    "quota.downgrade.banner": "Over the free 50-photo limit — delete extras or subscribe to unlock",
    "quota.locked.badge": "Pro",
    "quota.locked.sheet.body": "The free plan displays your 50 most recent photos; older photos are locked. Subscribe to restore full access, or delete extra photos to free up space.",
    "quota.locked.sheet.cta.manage": "Manage Storage",
    "quota.locked.sheet.cta.renew": "Subscribe to Unlock All",
    "quota.locked.sheet.title": "Some photos are locked",
}
