# -*- coding: utf-8 -*-
"""English translation dictionary - Part 1 (M01 - M04)."""

# M01: InfoPlist (3) & Widget (47)
INFOPLIST_EN = {
    "CFBundleDisplayName": "MiLens",
    "NSPhotoLibraryUsageDescription": "MiLens needs access to your photo library to discover photos of your pal and create local profiles. Photos are never uploaded; edited works may be saved by system backups you have enabled.",
    "NSPhotoLibraryAddUsageDescription": "MiLens needs permission to save bead patterns, pal cards, and timeline export images to your Photos.",
}

WIDGET_EN = {
    "widget.common.daysLater": "In",
    "widget.common.daysLaterCount %lld": "In %lld days",
    "widget.common.join %@ %@": "%1$@ · %2$@",
    "widget.common.recent": "Recent",
    "widget.common.today": "Today",
    "widget.empty.createPetFirst": "Create a pal profile first",
    "widget.entity.anniversary": "Anniversary",
    "widget.entity.pet": "Pal",
    "widget.intents.anniversary.auto": "Auto",
    "widget.intents.anniversary.settings.description": "Select which pal's anniversary to display on the widget",
    "widget.intents.anniversary.settings.title": "Anniversary",
    "widget.intents.pet.all": "All Pals",
    "widget.intents.photoEcho.content": "Content",
    "widget.intents.photoEcho.contentSource": "Content Source",
    "widget.intents.photoEcho.settings.description": "Select which photos to display on the widget",
    "widget.intents.photoEcho.settings.title": "Photo Echo",
    "widget.intents.photoEcho.source.recentWork": "Recent Works",
    "widget.intents.photoEcho.source.todayOrRecent": "Today / Recent",
    "widget.intents.photoEcho.source.yearsAgoToday": "This Day in Past Years",
    "widget.intents.selectPet.description": "Select the pal profile to display in the widget",
    "widget.intents.selectPet.title": "Select Pal",
    "widget.lifeArchive.description": "See how long you have been together, plus recent photos and memories",
    "widget.lifeArchive.empty.noPhotos": "No photos yet",
    "widget.lifeArchive.name": "Life Archive",
    "widget.lifeArchive.stat.memories": "Memories",
    "widget.lifeArchive.stat.photos": "Photos",
    "widget.lifeArchive.stat.works": "Works",
    "widget.lockscreen.countdown.name": "Countdown",
    "widget.lockscreen.memory.createFile": "Add Pal",
    "widget.lockscreen.memory.description": "A memory with your pal and days together",
    "widget.lockscreen.memory.name": "A Memory",
    "widget.lockscreen.memory.pending": "Pending",
    "widget.photoEcho.description": "Relive today's photos and memories from past years",
    "widget.photoEcho.empty.noPhoto": "No photos yet",
    "widget.photoEcho.header %@": "MiLens · %@",
    "widget.photoEcho.name": "Photo Echo",
    "widget.stale.updated %@": "Updated %@",
    "widget.stale.waitingSync": "Waiting for sync",
    "widget.upcoming.daysTogether.adoption %lld": "%lld days since adoption",
    "widget.upcoming.daysTogether.birthday %lld": "%lld days old",
    "widget.upcoming.daysTogether.memorial %lld": "Recorded for %lld days",
    "widget.upcoming.description": "Counts down to your pal's next important day, automatically picking the closest anniversary",
    "widget.upcoming.empty.missing": "Profile not found",
    "widget.upcoming.empty.none": "No upcoming anniversaries",
    "widget.upcoming.name": "Upcoming Anniversaries",
    "widget.upcoming.remainingDays %lld": "In %lld days",
    "widget.upcoming.today": "Today",
}

# M02: Plurals (21)
PLURALS_EN = {
    "home.memory.yearsAgo %lld": {
        "one": "1 year ago today",
        "other": "%lld years ago today",
    },
    "home.photoCount %lld": {
        "one": "Photo #%lld",
        "other": "Photo #%lld",
    },
    "notify.memory.yearsAgo %lld %@": {
        "one": "1 year ago today: %@",
        "other": "%lld years ago today: %@",
    },
    "notify.timemachine.asking %lld %@": {
        "one": "What was %@ doing 1 year ago today?",
        "other": "What was %@ doing %lld years ago today?",
    },
    "notify.timemachine.companion %lld %@": {
        "one": "%@ was by your side 1 year ago today",
        "other": "%@ was by your side %lld years ago today",
    },
    "notify.timemachine.flight %lld": {
        "one": "Time flies — 1 year ago today",
        "other": "Time flies — %lld years ago today",
    },
    "notify.timemachine.flightNote %lld %@": {
        "one": "Time flies — 1 year ago today, %@",
        "other": "Time flies — %lld years ago today, %@",
    },
    "notify.timemachine.title %lld": {
        "one": "Today, 1 year ago",
        "other": "Today, %lld years ago",
    },
    "paywall.cta.trial %lld": {
        "one": "Free trial · %d day",
        "other": "Free trial · %d days",
    },
    "paywall.trial.hint %lld": {
        "one": "First %d day free",
        "other": "First %d days free",
    },
    "pet.age.months %lld": {
        "one": "1 month",
        "other": "%lld months",
    },
    "pet.age.years %lld": {
        "one": "1 year",
        "other": "%lld years",
    },
    "pet.card.birthdayYears %lld": {
        "one": "1st Birthday",
        "other": "Birthday #%lld",
    },
    "pet.card.daysHome %lld": {
        "one": "Home for 1 day",
        "other": "Home for %lld days",
    },
    "pet.companionship.arrived %lld": {
        "one": "Home for 1 day",
        "other": "Home for %lld days",
    },
    "pet.companionship.together %lld": {
        "one": "Together for 1 day",
        "other": "Together for %lld days",
    },
    "pet.daysTogether %lld": {
        "one": "Together for 1 day",
        "other": "Together for %lld days",
    },
    "timeline.export.entryCount %lld": {
        "one": "1 record",
        "other": "%lld records",
    },
    "timeline.month %lld": {
        "one": "Month %lld",
        "other": "Month %lld",
    },
    "timeline.previewDaysLeft %lld": {
        "one": "1 day left in full preview",
        "other": "%lld days left in full preview",
    },
    "timeline.year %lld": {
        "one": "Year %lld",
        "other": "Year %lld",
    },
}

# M03: Onboarding (136)
ONBOARDING_EN = {
    "onboarding.candidates.body %@": "These are candidate photos matching %@'s profile. Please confirm to import.",
    "onboarding.candidates.cta %lld %@": "Confirm %lld photos to %@'s archive",
    "onboarding.candidates.status.pending": "Pending",
    "onboarding.candidates.status.selected": "Selected",
    "onboarding.candidates.tab.all %lld": "All %lld",
    "onboarding.candidates.tab.pending %lld": "Pending %lld",
    "onboarding.candidates.tab.selected %lld": "Selected %lld",
    "onboarding.candidates.title": "Familiar Moments Found",
    "onboarding.createArchive.body": "Create a profile for your pal first,\nthen scan your library anytime.",
    "onboarding.createArchive.card.body": "Register photos to recognize their features\nand confirm matches.",
    "onboarding.createArchive.card.waiting": "Waiting for your first pal",
    "onboarding.createArchive.cta": "Create First Pal Profile",
    "onboarding.createArchive.mark": "ARCHIVE 001",
    "onboarding.createArchive.nameLabel": "What is their name?",
    "onboarding.createArchive.namePlaceholder": "e.g. Luna",
    "onboarding.createArchive.note": "Each pal profile automatically organizes photos during scans.",
    "onboarding.createArchive.saveFailed": "Save failed. Please try again.",
    "onboarding.createArchive.species.other": "Other",
    "onboarding.createArchive.speciesLabel": "Choose category",
    "onboarding.createArchive.title": "Create a profile for your pal",
    "onboarding.feature.badge": "Profile Photo",
    "onboarding.feature.baseline": "FEATURE BASELINE",
    "onboarding.feature.cta": "Feature Profile",
    "onboarding.feature.done.body": "MiLens uses feature similarity baselines for recognition.\nYou can manually adjust any uncertain matches.",
    "onboarding.feature.done.count %lld": "%lld photos registered",
    "onboarding.feature.done.cta": "Scan Photo Library",
    "onboarding.feature.done.localOnly": "On-Device Only",
    "onboarding.feature.done.next.body": "We will scan all photos in your library.\nScanning only generates candidate photos for confirmation.",
    "onboarding.feature.done.next.note": "You can pause scanning or revoke permissions anytime.",
    "onboarding.feature.done.next.title": "Next: Full scan of your photo library",
    "onboarding.feature.done.title %@": "%@'s feature baseline\nis ready",
    "onboarding.feature.guidance.angle": "Different angles",
    "onboarding.feature.guidance.angle.detail": "Front, side, and full body",
    "onboarding.feature.guidance.clarity": "Clear and visible",
    "onboarding.feature.guidance.clarity.detail": "Avoid blurry or dark photos",
    "onboarding.feature.guidance.single %@": "Only %@",
    "onboarding.feature.guidance.single.detail": "Avoid multi-pal photos",
    "onboarding.feature.intro.body %@": "Select photos of only %@ from different angles.\nAll recognition runs entirely on your device.",
    "onboarding.feature.intro.title": "Pick 8–15 photos to build baseline",
    "onboarding.feature.maxCount %lld": "Up to %lld photos",
    "onboarding.feature.minCount %lld": "At least %lld photos",
    "onboarding.feature.processing.body %lld": "Using %lld photos as comparison baseline.\nPhotos are never uploaded to servers.",
    "onboarding.feature.processing.cta": "Building Baseline...",
    "onboarding.feature.processing.status": "Building feature baseline",
    "onboarding.feature.processing.title %@": "Building %@'s\nfeature baseline on device",
    "onboarding.feature.ready %lld": "%lld photos ready",
    "onboarding.feature.ready.note %@": "Only used as comparison baseline for %@",
    "onboarding.feature.registerFailed %@": "Registration failed: %@",
    "onboarding.feature.registered %lld": "%lld photos registered",
    "onboarding.feature.reselect %lld": "Reselect (selected %lld)",
    "onboarding.feature.select": "Select 8–15 photos",
    "onboarding.feature.stage.extract": "Extracting features",
    "onboarding.feature.stage.quality": "Assessing photo quality",
    "onboarding.feature.stage.summarize %@": "Generating feature baseline for %@",
    "onboarding.import.body %lld": "Writing %lld confirmed photos to local archive.\nPhotos never leave this device.",
    "onboarding.import.count %lld": "%lld photos being imported",
    "onboarding.import.cta %@": "Enter %@'s Archive",
    "onboarding.import.keep.body": "Every day together is worth remembering. MiLens organizes your scattered moments into a dedicated digital archive.",
    "onboarding.import.keep.title": "Keep the memories safe",
    "onboarding.import.lens.title": "Organized in MiLens",
    "onboarding.import.local.body": "Photos are never uploaded to the cloud",
    "onboarding.import.local.title": "Saved only on this device",
    "onboarding.import.localMark": "LOCAL ARCHIVE",
    "onboarding.import.longArchiveMark": "LIFE LONG ARCHIVE",
    "onboarding.import.memoryMark": "MEMORY SAFEKEEPING",
    "onboarding.import.memoryTitle %@": "%@'s first photos are archived",
    "onboarding.import.note": "All data is stored locally. You can delete or re-classify anytime.",
    "onboarding.import.stage.archive %@": "Writing to %@'s archive",
    "onboarding.import.stage.copy": "Saving originals",
    "onboarding.import.stage.thumbnails": "Generating thumbnails",
    "onboarding.import.stat.originals": "Originals",
    "onboarding.import.stat.pets": "Pals",
    "onboarding.import.stat.thumbnails": "Thumbnails",
    "onboarding.import.title %@": "Saving\n%@'s memories",
    "onboarding.import.writing %lld": "Writing %lld photos...",
    "onboarding.overline.candidates": "ALBUM / CANDIDATES",
    "onboarding.overline.createArchive": "LIFE ARCHIVE · PAL PROFILE",
    "onboarding.overline.featureDone": "FEATURE REGISTER · READY",
    "onboarding.overline.featureIntro": "FEATURE REGISTER · 8–15 PHOTOS",
    "onboarding.overline.featureProcessing": "FEATURE REGISTER · PROCESSING",
    "onboarding.overline.fullScan": "LOCAL SCAN · BASELINE READY",
    "onboarding.overline.importing": "ARCHIVE IMPORT · SAVING",
    "onboarding.overline.privacy": "FIRST LIGHT · PRIVACY SUMMARY",
    "onboarding.overline.success": "ARCHIVE / ENTRY",
    "onboarding.overline.welcome": "FIRST LIGHT · WELCOME",
    "onboarding.privacy.auth.denied": "Photo permission not granted",
    "onboarding.privacy.auth.denied.hint": "Please enable in Settings → Privacy → Photos to allow scanning candidate photos.",
    "onboarding.privacy.auth.full": "Full photo library access granted",
    "onboarding.privacy.auth.limited": "Limited photo access granted",
    "onboarding.privacy.body": "MiLens only reads photos within your authorized scope.\nNothing is imported until you confirm.",
    "onboarding.privacy.card.body": "Photos are never uploaded to cloud servers",
    "onboarding.privacy.card.note": "On-Device · Private",
    "onboarding.privacy.card.title": "On-Device Only",
    "onboarding.privacy.cta": "Authorize & Continue",
    "onboarding.privacy.hint": "You can change photo library access scope in System Settings anytime.",
    "onboarding.privacy.onDevice": "ON DEVICE",
    "onboarding.privacy.requesting": "Requesting authorization...",
    "onboarding.privacy.rule.confirm": "You decide what gets imported",
    "onboarding.privacy.rule.confirm.detail": "Manual confirmation for uncertain photos",
    "onboarding.privacy.rule.leave": "Photos never leave your device",
    "onboarding.privacy.rule.leave.detail": "No server uploads",
    "onboarding.privacy.rule.local": "Local processing only",
    "onboarding.privacy.rule.local.detail": "Thumbnails processed on device",
    "onboarding.privacy.title": "Your photos\nstay on this device",
    "onboarding.scan.body %@": "Comparing against %@'s feature baseline.\nCandidate photos will be shown for your confirmation.",
    "onboarding.scan.candidates.hint": "Confirm matches after scan completes",
    "onboarding.scan.candidates.title": "Candidate photos found",
    "onboarding.scan.complete": "Scan Complete",
    "onboarding.scan.finish": "Finish Scan",
    "onboarding.scan.found %lld %@": "Found %lld photos that may feature %@.\nReview and confirm them.",
    "onboarding.scan.incomplete": "Scan in progress",
    "onboarding.scan.incomplete.hint": "You can pause now and continue from the album page anytime.",
    "onboarding.scan.none %@": "No photos matching %@ found.\nYou can manually import photos later.",
    "onboarding.scan.progress %lld %lld": "Scanning photos... %lld/%lld",
    "onboarding.scan.scanning": "Scanning library on device...",
    "onboarding.scan.skip": "Skip scanning, confirm later",
    "onboarding.scan.stage.thumbnails": "Reading thumbnails from library",
    "onboarding.scan.status.comparing": "Scanning · Comparing",
    "onboarding.scan.status.completed": "Scanning · Completed",
    "onboarding.scan.title": "Full scan\nof your photo library",
    "onboarding.scan.unit": "photos",
    "onboarding.scan.viewCandidates %lld": "View %lld candidate photos",
    "onboarding.status.done": "Done",
    "onboarding.status.inProgress": "In Progress",
    "onboarding.status.later": "Later",
    "onboarding.welcome.agreePrefix": "I have read and agree to",
    "onboarding.welcome.archiveMark": "EMPTY ARCHIVE / 00",
    "onboarding.welcome.cta": "Create First Pal Profile",
    "onboarding.welcome.emptyBody": "The archive is empty.\nLet's start with your first pal.",
    "onboarding.welcome.emptyNote": "Photos stay on device, kept safe locally",
    "onboarding.welcome.emptyTitle": "Waiting for your first pal",
    "onboarding.welcome.hero": "Keep their whole life\nright here",
    "onboarding.welcome.privacyLink": "Privacy Policy",
    "onboarding.welcome.waypoint.confirm": "Confirm to import",
    "onboarding.welcome.waypoint.deletable": "Delete anytime",
    "onboarding.welcome.waypoint.organize": "Local archive",
}

# M04: Pals (104)
PALS_EN = {
    "avatar.crop.failed": "Unable to process avatar image",
    "avatar.crop.hint": "Drag to adjust position",
    "pet.add.title": "Add a Pal",
    "pet.age.join": " ",
    "pet.age.unknown": "Unknown",
    "pet.card.fallbackSubtitle": "A day to remember",
    "pet.card.fallbackTitle": "This Day",
    "pet.card.subtitle %@ %@": "%@ · %@",
    "pet.companionship.family %@ %lld": "%@ has been family for %lld days",
    "pet.companionship.future": "Companionship has not started yet",
    "pet.companionship.unknown": "Companionship days unknown",
    "pet.edit.adoptionDay": "Adoption Day",
    "pet.edit.avatar.change": "Change Avatar",
    "pet.edit.avatar.choose": "Choose Avatar",
    "pet.edit.avatar.footer": "Select a photo to crop as circular avatar",
    "pet.edit.birthday": "Birthday",
    "pet.edit.clearDates": "Clear Dates",
    "pet.edit.delete.message %@": "Are you sure you want to delete %@'s profile? Original photos in your library won't be deleted.",
    "pet.edit.delete.title": "Delete Pal Profile",
    "pet.edit.feature.failed %@": "Registration failed: %@",
    "pet.edit.feature.footer.new %lld %lld": "Pick %lld–%lld photos from different angles to auto-match new photos during scans.",
    "pet.edit.feature.footer.update %lld %lld": "Re-registering features requires %lld–%lld photos",
    "pet.edit.feature.maxPhotos %lld": "Up to %lld photos",
    "pet.edit.feature.minPhotos %lld": "At least %lld photos",
    "pet.edit.feature.progress %lld/%lld": "Extracting features %lld/%lld",
    "pet.edit.feature.registeredCount %lld": "%lld baseline photos registered",
    "pet.edit.feature.registering": "Registering features...",
    "pet.edit.feature.reselect %lld": "Reselect (%lld selected)",
    "pet.edit.feature.section": "Visual Features",
    "pet.edit.feature.select %lld %lld": "Select %lld–%lld photos",
    "pet.edit.gender": "Gender",
    "pet.edit.gender.female": "Girl",
    "pet.edit.gender.male": "Boy",
    "pet.edit.gender.unknown": "Secret",
    "pet.edit.memo": "Notes",
    "pet.edit.memo.placeholder": "Write something about them (favorite treats, personality, etc.)...",
    "pet.edit.memo.section": "Memo",
    "pet.edit.name": "Name",
    "pet.edit.name.placeholder": "Enter name",
    "pet.edit.notes.tooLong %lld": "Notes cannot exceed %lld characters",
    "pet.edit.reregister.hint": "Re-registering will replace current visual features.",
    "pet.edit.reregister.title": "Re-register Features",
    "pet.edit.save": "Save",
    "pet.edit.saving": "Saving...",
    "pet.edit.section.basic": "Basic Info",
    "pet.edit.section.importantDates": "Important Dates",
    "pet.edit.species": "Species",
    "pet.edit.species.cat": "Cat",
    "pet.edit.species.cat_formal": "Cat",
    "pet.edit.species.dog": "Dog",
    "pet.edit.species.dog_formal": "Dog",
    "pet.edit.species.other": "Other",
    "pet.edit.species.other_formal": "Other",
    "pet.edit.title.edit": "Edit Pal Profile",
    "pet.edit.title.new": "Add a Pal",
    "pet.form.countLimit %lld": "Free plan supports up to %lld pal profile. Upgrade to Pro for up to 20 pals.",
    "pet.form.name.required": "Please enter a name for your pal",
    "pet.gender.female": "Girl",
    "pet.gender.male": "Boy",
    "pet.gender.unknown": "Secret",
    "pet.profile.action.edit": "Edit Profile",
    "pet.profile.action.generateBead": "Make Bead Pattern",
    "pet.profile.action.makeCard": "Create Pal Card",
    "pet.profile.action.more": "More Actions",
    "pet.profile.action.scanMore": "Scan for Photos",
    "pet.profile.action.timeline": "Growth Timeline",
    "pet.profile.daysHomeTitle": "Home Together",
    "pet.profile.daysLabel": "Days Together",
    "pet.profile.empty.cta": "Import Photos",
    "pet.profile.empty.subtitle": "Scan or import photos to start building the timeline",
    "pet.profile.empty.title": "No Photos Archived Yet",
    "pet.profile.eyebrow": "A Lifetime Archive",
    "pet.profile.lifeMark %lld": "LIFE MARK · %lld",
    "pet.profile.loadFailed": "Failed to Load Pal Profile",
    "pet.profile.memoryTitle": "A Memory",
    "pet.profile.milestones.title": "Milestones",
    "pet.profile.noPhoto": "No photo",
    "pet.profile.noProfile": "No Pal Profile",
    "pet.profile.pinned.empty": "Pin precious memories here",
    "pet.profile.pinned.section": "Pinned Memories · Page 01",
    "pet.profile.pinnedTitle": "Pinned Memories",
    "pet.profile.quickBead.cta": "Create Pattern",
    "pet.profile.quickBead.hint": "Turn their favorite photo into a bead pattern",
    "pet.profile.quickBead.title": "Bead Studio",
    "pet.profile.section.anniversaries": "Anniversaries",
    "pet.profile.section.growth": "Growth Records",
    "pet.profile.section.memories": "Precious Memories",
    "pet.profile.section.recentPhotos": "Recent Photos",
    "pet.profile.speciesAge %@ %@": "%@ · %@",
    "pet.profile.stat.days": "Days Together",
    "pet.profile.stat.memories": "Memories",
    "pet.profile.stat.photos": "Photos",
    "pet.profile.stat.works": "Works",
    "pet.species.cat": "Cat",
    "pet.species.dog": "Dog",
    "pet.species.unknown": "Unknown",
    "petcard.overline": "PAL CARD",
    "pets.empty.cta": "Add a Pal",
    "pets.empty.title": "No Pal Profiles Yet",
    "pets.list.add": "Add Pal",
    "pets.list.manage": "Manage Pals",
    "pets.list.title": "Pals",
}
