# -*- coding: utf-8 -*-
"""English translation dictionary - Part 4 (Supplement 762 keys)."""

SUPPLEMENT_EN = {
    "redpacket.action.create": "Create Red Packet",
    "redpacket.action.saveDraft": "Save Draft",
    "redpacket.action.useTemplate": "Use Template",
    "redpacket.adjust.brightness": "Brightness",
    "redpacket.adjust.contrast": "Contrast",
    "redpacket.adjust.saturation": "Saturation",
    "redpacket.adjust.warmth": "Warmth",
    "redpacket.banner.title": "WeChat Red Packet Cover Studio",
    "redpacket.banner.subtitle": "Custom covers for your pal",
    "redpacket.card.title": "Red Packet Cover",
    "redpacket.cover.adjust": "Adjust Cover",
    "redpacket.cover.crop": "Crop Cover",
    "redpacket.cover.export": "Export Cover",
    "redpacket.cover.preview": "Preview Cover",
    "redpacket.cover.style": "Cover Style",
    "redpacket.crop.auto": "Smart Auto-Crop",
    "redpacket.crop.custom": "Custom Crop",
    "redpacket.crop.guideline": "Follow WeChat Cover Specifications",
    "redpacket.crop.hint": "Keep key pal features inside the central safe zone",
    "redpacket.crop.preview": "Crop Preview",
    "redpacket.crop.scale": "Scale",
    "redpacket.draft.delete": "Delete Draft",
    "redpacket.draft.edit": "Edit Draft",
    "redpacket.draft.title": "Cover Drafts",
    "redpacket.export.complete": "Export Complete",
    "redpacket.export.guide": "How to Upload to WeChat",
    "redpacket.export.hint": "Image meets WeChat official 957×1278 standard",
    "redpacket.export.image": "Save Cover Image",
    "redpacket.export.instructions": "Upload the exported PNG on the WeChat Red Packet Cover Open Platform.",
    "redpacket.export.success": "Cover successfully exported to Photos",
    "redpacket.filter.boost": "Color Boost",
    "redpacket.filter.fresh": "Fresh",
    "redpacket.filter.gentle": "Gentle",
    "redpacket.filter.lively": "Lively",
    "redpacket.filter.none": "No Filter",
    "redpacket.frame.gold": "Gold Ribbon",
    "redpacket.frame.lantern": "Red Lantern",
    "redpacket.frame.lucky": "Lucky Knot",
    "redpacket.frame.none": "No Frame",
    "redpacket.frame.paw": "Lucky Paws",
    "redpacket.frame.spring": "Spring Flowers",
    "redpacket.frame.title": "Decorative Frames",
    "redpacket.guideline.body": "WeChat Red Packet Cover requires a 957×1278 PNG under 500 KB.",
    "redpacket.guideline.title": "Cover Guidelines",
    "redpacket.material.upload": "Upload Photo",
    "redpacket.overlay.banner": "New Year Blessings",
    "redpacket.overlay.blessing": "Best Wishes",
    "redpacket.overlay.fortune": "Good Fortune",
    "redpacket.overlay.lucky": "Good Luck",
    "redpacket.overlay.title": "Festive Text",
    "redpacket.palette.festive": "Festive Red",
    "redpacket.palette.gold": "Golden Yellow",
    "redpacket.palette.pal": "Pal Natural",
    "redpacket.palette.spring": "Spring Pink",
    "redpacket.palette.warm": "Warm Amber",
    "redpacket.preview.empty": "Select a photo to preview cover",
    "redpacket.preview.full": "Full Preview",
    "redpacket.preview.openState": "Opened Cover",
    "redpacket.preview.receive": "Receiving Screen",
    "redpacket.preview.send": "Sending Screen",
    "redpacket.quality.badge.error": "Review Needed",
    "redpacket.quality.badge.warning": "Warning",
    "redpacket.quality.check": "Check Quality",
    "redpacket.quality.dimensions": "Dimensions",
    "redpacket.quality.dimensions.detail": "Matches 957×1278 standard",
    "redpacket.quality.fileSize": "File Size",
    "redpacket.quality.fileSize.detail": "Under 500 KB limit",
    "redpacket.quality.level.error": "Does Not Meet Standards",
    "redpacket.quality.level.warning": "Minor Issues Found",
    "redpacket.quality.passed": "Passed All Quality Checks",
    "redpacket.quality.safeArea": "Safe Area",
    "redpacket.quality.safeArea.detail": "Subject is safely centered",
    "redpacket.rules.description": "Please review WeChat official cover creation rules",
    "redpacket.scene.bubble.desc": "Displayed in 1-on-1 and group chats",
    "redpacket.scene.cover.desc": "Displayed when tapping to open packet",
    "redpacket.scene.details.desc": "Displayed on transaction details page",
    "redpacket.scene.story.desc": "Displayed in cover story swipe page",
    "redpacket.spec.format": "Format: PNG / JPG",
    "redpacket.spec.resolution": "Resolution: 957 × 1278",
    "redpacket.spec.size": "File Size: < 500 KB",
    "redpacket.sticker.blessing": "Blessing Seal",
    "redpacket.sticker.fireworks": "Fireworks",
    "redpacket.sticker.ingot": "Gold Ingot",
    "redpacket.sticker.lantern": "Red Lantern",
    "redpacket.sticker.lucky": "Lucky Charm",
    "redpacket.sticker.paw": "Golden Paw",
    "redpacket.sticker.title": "Festive Stickers",
    "redpacket.style.festive": "Festive",
    "redpacket.template.auspicious": "Auspicious Year",
    "redpacket.template.blessing": "New Year Blessing",
    "redpacket.template.fortune": "Fortune & Wealth",
    "redpacket.template.happiness": "Double Happiness",
    "redpacket.template.longevity": "Healthy & Happy",
    "redpacket.template.peace": "Peace & Joy",
    "redpacket.template.prosperity": "Prosperity",
    "redpacket.template.reunion": "Warm Reunion",
    "redpacket.template.springFestival": "Spring Festival Celebration",
    "redpacket.text.add": "Add Text",
    "redpacket.text.color": "Text Color",
    "redpacket.text.font": "Text Font",
    "redpacket.text.placeholder": "Enter blessing...",
    "redpacket.text.size": "Text Size",
    "redpacket.text.style": "Text Style",
    "redpacket.upload.action": "Upload to WeChat",
    "redpacket.upload.hint": "Follow official WeChat submission steps",
    "redpacket.upload.title": "Upload Guidance",
    "redpacket.workshop.intro": "Create customized WeChat red packet covers featuring your pal.",
    "redpacket.workshop.start": "Get Started",
    "settings.backup.comingSoon": "Cloud backup coming in a future update",
    "settings.backup.confirmAction": "Confirm Backup",
    "settings.backup.confirmHint": "Backup includes pal profiles, metadata, and archived photos",
    "settings.backup.confirmPets %lld": "%lld Pal Profiles",
    "settings.backup.confirmPhotos %lld": "%lld Photos",
    "settings.backup.confirmSize %@": "Estimated Size: %@",
    "settings.backup.confirmTitle": "Backup Summary",
    "settings.backup.exportReady": "Backup Ready",
    "settings.backup.exportReadyHint": "Your offline backup file is ready to share or save",
    "settings.backup.failed": "Backup process encountered an error",
    "settings.backup.hint.body": "Backups are stored offline. You can transfer backup files via AirDrop, Files, or cloud drives.",
    "settings.backup.hint.title": "Offline Backup Tips",
    "settings.backup.lastBackup %@": "Last Backup: %@",
    "settings.backup.modeUpdated": "Backup Mode Updated",
    "settings.backup.modeUpdatedMessage": "Backup preferences have been saved",
    "settings.backup.multiVolumeHint %lld": "Split into %lld volumes due to large library size",
    "settings.backup.neverBackup": "No backup records found",
    "settings.backup.ok": "OK",
    "settings.backup.phase.collecting": "Collecting pal data...",
    "settings.backup.phase.compressing": "Compressing backup archive...",
    "settings.backup.phase.copying": "Copying photo files...",
    "settings.backup.phase.done": "Backup finished",
    "settings.backup.phase.progress %lld %@": "%1$lld%% (%2$@)",
    "settings.backup.photoBackupMode": "Photo Storage Mode",
    "settings.backup.photoBackupMode.footer": "Choose whether to include full-resolution originals in backups",
    "settings.backup.proOnly": "Pro Feature",
    "settings.backup.restore": "Restore",
    "settings.backup.restoreComplete": "Restore Finished",
    "settings.backup.restoreSummary %lld %lld %lld %lld": "Restored %1$lld pals, %2$lld photos, %3$lld works, %4$lld memories",
    "settings.backup.share": "Share Backup File",
    "settings.backup.zipHint": "ZIP Archive Format",
    "settings.bellShake.all": "All Reminders",
    "settings.bellShake.anniversaryOnly": "Anniversaries Only",
    "settings.bellShake.newPhotoOnly": "New Photos Only",
    "settings.bellShake.off": "Off",
    "settings.bellShake.title": "Memorial Bell Shake",
    "settings.footer.privacy": "All photos and data stay on your device.",
    "settings.privacy.badge.body": "On-Device Processing",
    "settings.privacy.badge.title": "Privacy First",
    "settings.pro.card.body": "Unlock unlimited bead patterns, 20 pal profiles, and full timeline history.",
    "settings.pro.card.body.active": "You have full access to all Pro features.",
    "settings.pro.card.cta": "Upgrade to Pro",
    "settings.pro.card.cta.active": "Manage",
    "settings.pro.card.headline": "MiLens Pro",
    "settings.pro.card.headline.active": "MiLens Pro Active",
    "settings.section.preferences": "Preferences",
    "settings.subtitle.suffix": " · Digital Life Archive",
    "recovery.databaseError": "Database error detected",
    "recovery.description": "You can attempt automatic repair or rebuild local data.",
    "recovery.exportEmergency": "Emergency Data Export",
    "recovery.help": "Recovery Help",
    "recovery.notice": "Original photos in your system photo library are never deleted.",
    "recovery.rebuilding": "Rebuilding local database...",
    "recovery.status": "Recovery Status",
    "privacy.guarantee.body": "No photos leave your phone. All AI processing runs on device.",
    "privacy.guarantee.title": "100% Local Processing",
    "create.bead.effectCount %lld": "%lld Effects Available",
    "create.bead.materialCount %lld %lld": "%1$lld Colors · %2$lld Beads Total",
    "create.bead.palette.choose": "Select Palette",
    "create.bead.preview.hint": "Pinch to zoom and view individual bead codes",
    "create.bead.style.choose": "Select Art Style",
    "create.card.export": "Export Pal Card",
    "create.card.generate": "Generate Card",
    "create.card.preview": "Card Preview",
    "create.card.style": "Card Style",
    "create.card.theme": "Card Theme",
    "create.draft.list": "Saved Drafts",
    "create.draft.load": "Load Draft",
    "create.draft.save": "Save Draft",
    "create.export.pdf": "Export PDF",
    "create.export.png": "Export PNG",
    "create.filter.style": "Style Filter",
    "create.palette.custom": "Custom Palette",
    "create.palette.default": "Default Palette",
    "create.palette.mard": "MARD Palette",
    "create.pattern.grid": "Show Grid",
    "create.pattern.numbers": "Show Color Numbers",
    "create.pattern.zoom": "Zoom In",
    "create.redpacket.export": "Export Cover",
    "create.redpacket.make": "Make Red Packet",
    "create.save.libraryFailed %@": "Failed to save to Photos: %@",
    "create.save.success": "Saved successfully",
    "create.size.choose": "Select Pegboard Size",
    "create.size.large": "Large",
    "create.size.medium": "Medium",
    "create.size.small": "Small",
    "create.style.illustration": "Illustration",
    "create.style.pixel": "Pixel Art",
    "create.style.portrait": "Portrait",
    "create.timeline.export": "Export Timeline Poster",
    "create.timeline.generate": "Generate Poster",
    "bead.palette.details": "Palette Details",
    "bead.palette.mardColors": "MARD Standard Colors",
    "bead.palette.perlerColors": "Perler Standard Colors",
    "bead.result.boardInfo %lld %lld": "%1$lld × %2$lld Boards",
    "bead.result.colorDetails": "Color Code Breakdown",
    "bead.result.exportPdf": "Export A4 PDF",
    "bead.result.materialSortedBy %lld": "%lld Colors · Sorted by Quantity",
    "bead.result.printPdf": "Print Pattern PDF",
    "bead.result.savePhoto": "Save to Photos",
    "bead.result.shareSheet": "Share Pattern",
    "timeline.addMemory": "Add Memory",
    "timeline.addMemory.bodyPlaceholder": "Write down this moment with your pal...",
    "timeline.addMemory.comingSoon": "Memory creation coming soon",
    "timeline.addMemory.content": "Memory Content",
    "timeline.addMemory.date": "Memory Date",
    "timeline.addMemory.noPet": "No pal selected",
    "timeline.addMemory.noPhoto": "No photo attached",
    "timeline.addMemory.options": "Memory Options",
    "timeline.addMemory.pet": "Pal",
    "timeline.addMemory.pinned": "Pin Memory",
    "timeline.addMemory.relatedPhoto": "Related Photo",
    "timeline.addMemory.save": "Save Memory",
    "timeline.addMemory.saveFailed": "Failed to save memory",
    "timeline.addMemory.titlePlaceholder": "Memory Title",
    "timeline.addMemory.titleRequired": "Please enter a title for this memory",
    "timeline.allPets": "All Pals",
    "timeline.chapter.subtitle": "Growth Chapter",
    "timeline.chapter.together %lld": "Day %lld Together",
    "timeline.event.adoption %@": "%@'s Adoption Day",
    "timeline.event.birthday %@": "%@'s Birthday",
    "timeline.exportFailed": "Timeline export failed",
    "timeline.exportFailedDetail %@": "Export failed: %@",
    "timeline.filterAll": "All Pals",
    "timeline.lockedBannerCTA": "Unlock Lifetime History",
    "timeline.lockedBannerTitle": "Free plan includes past 1 year of timeline",
    "timeline.lockedEmptyBody": "Upgrade to Pro to unlock your pal's full lifetime memories.",
    "timeline.lockedEmptyTitle": "Earlier Memories are Locked",
    "timeline.memoryType.photo": "Photo",
    "timeline.memoryType.text": "Text Story",
    "timeline.memoryType.work": "Bead Artwork",
    "timeline.photo.title %@": "%@'s Photo",
    "timeline.photo.title.default": "Memory Photo",
    "timeline.previewUnlockCTA": "Unlock Full History",
    "timeline.reference.update.subtitle %@": "Update feature baseline with photos of %@",
    "timeline.reference.update.title %@": "Update %@'s Features",
    "timeline.type.adoption": "Adoption",
    "timeline.type.birthday": "Birthday",
    "timeline.viewProBenefits": "View Pro Benefits",
    "timeline.work.fromPhoto": "Created from Photo",
    "timeline.work.saved": "Saved Artwork",
    "home.card.growth": "Growth Timeline",
    "home.card.memories": "Past Flashbacks",
    "home.card.quickBead": "Bead Studio",
    "home.card.stats": "Archive Stats",
    "notify.timeMachine.daily": "Daily 9:00 AM Time Machine memory",
    "notify.timeMachine.note": "Flashback to this day in past years",
    "album.candidates.continue %lld": "Continue Confirming (%lld remaining)",
    "album.candidates.tabAll %lld": "All %lld",
    "album.candidates.tabPending %lld": "Pending %lld",
    "album.candidates.tabSelected %lld": "Selected %lld",
    "album.candidates.title": "Candidate Photos",
    "album.empty.noCandidates": "No candidate photos",
    "album.empty.noPals": "No pal profiles created yet",
    "album.filter.date": "Filter by Date",
    "album.filter.pal": "Filter by Pal",
    "album.petSelect.confirm %lld": "Confirm (%lld Selected)",
    "album.petSelect.confirmTo %@": "Confirm and assign to %@",
    "album.petSelect.createPal": "Add New Pal",
    "album.petSelect.importTarget %@": "Import into %@'s Archive",
    "album.petSelect.petMeta %@ %lld": "%1$@ · %2$lld Photos",
    "album.petSelect.quotaNote %lld %lld": "Confirming will import photos; usage %1$lld / %2$lld",
    "album.petSelect.title": "Assign to Pal Profile",
    "album.quota.banner": "Storage Limit Reached",
    "album.quota.title %lld": "%lld Free Photo Limit",
    "album.quota.upgrade": "Upgrade to Pro for Unlimited Storage",
    "album.scan.complete": "Scan Finished",
    "album.scan.inProgress": "Scanning library...",
    "album.scan.title": "Scan Photos",
    "album.success.dateMark %@ %@": "%1$@ · %2$@",
    "album.success.joined %@": "Added to %@'s Archive",
    "album.success.title %lld": "%lld Photos Archived",
    "album.success.viewPhotos %@": "View %@'s Photos",
    "picker.action.add": "Add Selected",
    "picker.action.cancel": "Cancel",
    "picker.action.done": "Done",
    "picker.action.selectAll": "Select All",
    "picker.filter.date": "Date",
    "picker.filter.type": "Type",
    "picker.grid.title": "Select Photos",
    "picker.prompt.maxReached %lld": "Maximum %lld photos selected",
    "picker.selected.none": "No photos selected",
    "upload.action.wechatShare": "Share to WeChat",
    "upload.headline": "Import Pal Photos",
    "upload.platformNote": "Photos are processed locally on device",
    "upload.proof.spec": "Specifications Verified",
    "upload.proof.title": "Proofing Preview",
    "upload.proof.watermark": "MiLens Archive",
    "upload.step.01.desc": "Pick candidate photos of your pal",
    "upload.step.01.title": "Select Photos",
    "upload.step.02.desc": "Confirm which pal each photo belongs to",
    "upload.step.02.title": "Assign to Pal",
    "upload.step.03.desc": "Assess sharpness and visual quality",
    "upload.step.03.title": "Quality Check",
    "upload.step.04.desc": "Save into your digital life archive",
    "upload.step.04.title": "Archive Photos",
    "source.businessCard.meta": "Pal Card Archive",
    "source.change": "Change Source",
    "source.petCard.meta": "Pal ID Card",
    "source.redPacket.meta": "Red Packet Cover",
    "editor.crop.aspect.free": "Freeform",
    "editor.crop.aspect.square": "Square (1:1)",
    "editor.crop.aspect.standard": "Standard (4:3)",
    "editor.crop.aspect.story": "Story (9:16)",
    "editor.cutout.brush": "Brush Refine",
    "editor.cutout.eraser": "Eraser",
    "editor.cutout.feather": "Edge Soften",
    "editor.cutout.invert": "Invert Selection",
    "editor.cutout.outline": "Add Outline",
    "editor.cutout.threshold": "Sensitivity",
    "decoration.sticker.category.daily": "Daily Life",
    "decoration.sticker.category.festive": "Festive",
    "decoration.sticker.category.memorial": "Memorial",
    "decoration.sticker.delete": "Delete Sticker",
    "decoration.sticker.duplicate": "Duplicate Sticker",
    "decoration.sticker.flip": "Flip Horizontal",
    "decoration.sticker.limit %lld": "Maximum %lld stickers allowed",
    "decoration.sticker.rotate": "Rotate",
    "share.action.saveLibrary": "Save to Photos",
    "share.action.share": "Share",
    "share.panel.destinations": "Share Destinations",
    "share.panel.more": "More Platforms",
    "share.panel.privacy": "Your photos remain private and are only shared when you confirm.",
    "share.panel.title": "Share with Friends",
    "share.platform.douyin": "TikTok / Douyin",
    "share.platform.moments": "WeChat Moments",
    "share.platform.rednote": "RED (Xiaohongshu)",
    "share.platform.wechat": "WeChat Friends",
    "share.preview.close": "Close",
    "share.preview.headline": "Share Keepsake",
    "share.sheet.morePlatforms": "More Platforms",
    "share.sheet.subtitle": "Share the sweet moments of your pal",
    "share.sheet.title": "Share",
    "share.sheet.watermarkHint": "Free export includes watermark · Pro removes watermark",
    "pet.edit.feature.guidance": "Feature Registration Guide",
    "pet.edit.feature.qualityHint": "Photos should clearly show your pal's face and distinct patterns.",
    "pet.edit.section.memo": "Personal Memo",
    "pet.form.avatar.select": "Select Avatar",
    "pet.form.birthday.choose": "Choose Birthday",
    "pet.form.gender.choose": "Select Gender",
    "pet.form.species.choose": "Select Species",
    "pet.profile.allMemories": "All Memories",
    "pet.profile.allPhotos": "All Photos",
    "pet.profile.allWorks": "All Bead Artworks",
    "petcard.field.age": "Age",
    "petcard.field.birthday": "Birthday",
    "petcard.field.breed": "Breed",
    "petcard.field.name": "Name",
    "petcard.field.species": "Species",
    "pets.list.empty": "No pal profiles created",
    "pets.list.subtitle": "Manage all your pal profiles in one place",
    "a11y.pets.avatarPhoto %@": "%@'s avatar photo",
    "a11y.editor.adjustSlider %@": "Adjust %@",
    "a11y.editor.layer %@": "Layer %@",
    "a11y.gallery.photoItem %@": "Photo captured on %@",
    "a11y.home.greeting": "Daily greeting",
    "a11y.tab.create": "Create tab",
    "a11y.tab.home": "Home tab",
    "a11y.tab.pets": "Pals tab",
    "a11y.tab.settings": "Settings tab",
    "help.q1": "How does MiLens find photos of my pal?",
    "help.a1": "MiLens scans your photo library on device using local AI models to discover photos featuring your pal, then lets you confirm matches.",
    "help.q2": "Are my photos uploaded to any servers?",
    "help.a2": "No. All photo analysis, categorization, and editing run 100% locally on your device. Your photos never leave your phone.",
    "help.q3": "How do I make a bead pattern?",
    "help.a3": "Go to the Create tab, select Bead Pattern, pick a photo of your pal, choose pegboard size and palette, then tap Generate.",
    "help.q4": "What benefits does MiLens Pro include?",
    "help.a4": "MiLens Pro unlocks up to 20 pal profiles, unlimited bead pattern generation, full lifetime growth timeline, and watermark-free exports."
}
