# -*- coding: utf-8 -*-
"""English translation dictionary - Last Batch (374 keys)."""

LAST_EN = {
    "a11y.bead.generate": "Generate bead pattern",
    "a11y.create.beadEntry": "Bead Pattern — select photo to begin",
    "a11y.create.petCardEntry": "Pal Card — select photo to begin",
    "a11y.editor.adjust": "Adjust",
    "a11y.editor.back": "Back",
    "a11y.editor.decorate": "Decorate",
    "a11y.editor.decoration.proBadge": "Pro Exclusive",
    "a11y.editor.decoration.unavailable": "Asset unavailable",
    "a11y.editor.deleteSticker": "Delete sticker",
    "a11y.editor.deleteText": "Delete text",
    "a11y.editor.redo": "Redo",
    "a11y.editor.removeFrame": "Remove frame",
    "a11y.editor.save": "Save",
    "a11y.editor.smart": "Smart enhance",
    "a11y.editor.undo": "Undo",
    "a11y.gallery.favorite": "Favorite",
    "a11y.gallery.photo": "Photo",
    "a11y.gallery.selected": "Selected",
    "a11y.home.bell": "Memorial Bell",
    "a11y.onboarding.back": "Previous step",
    "a11y.onboarding.privacyAgree": "I agree and understand",
    "a11y.petcard.generate": "Generate pal card",
    "a11y.photoView.assign": "Assign to pal",
    "a11y.photoView.edit": "Edit",
    "a11y.timeline.representativePhoto": "Featured photo",
    "action.saveDraft": "Save Draft",
    "action.saveShare": "Save & Share",
    "album.candidates.cardPending": "Pending",
    "album.candidates.cardSelected": "Selected",
    "album.candidates.quotaHint": "Unlock with MiLens Pro",
    "album.candidates.subtitle": "Album candidates subtitle",
    "album.petSelect.countUnit": "Album pal select count unit",
    "album.petSelect.defaultPetName": "Album pal select default pal name",
    "album.petSelect.defaultPetShort": "Album pal select default pal short",
    "album.petSelect.evidenceMark": "Album pal select evidence mark",
    "album.petSelect.importMark": "Album pal select import mark",
    "album.petSelect.newArchiveHint": "Album pal select new archive hint",
    "album.petSelect.newArchiveTitle": "Pal Profile",
    "album.petSelect.sectionTitle": "Pal Profile",
    "album.petSelect.selectedMark": "Album pal select selected mark",
    "album.quota.existingKept": "Album quota existing kept",
    "album.quota.later": "Album quota later",
    "album.quota.mark": "Album quota mark",
    "album.quota.resilience1.desc": "Album quota resilience1 desc",
    "album.quota.resilience1.title": "Album quota resilience1 title",
    "album.quota.resilience2.desc": "Album quota resilience2 desc",
    "album.quota.resilience2.title": "Album quota resilience2 title",
    "album.quota.resilience3.desc": "Album quota resilience3 desc",
    "album.quota.resilience3.title": "Album quota resilience3 title",
    "album.quota.subtitle": "Album quota subtitle",
    "album.quota.usedUp": "Album quota used up",
    "album.quota.viewPro": "Album quota view pro",
    "album.success.localBody": "Album success local body",
    "album.success.localTitle": "Album success local title",
    "album.success.privacyNote": "Album success privacy note",
    "album.success.statOriginal": "Album success stat original",
    "album.success.statPet": "Album success stat pal",
    "album.success.statThumbnail": "Album success stat thumbnail",
    "archive.preview.panelBody": "Archive preview panel body",
    "archive.preview.panelTitle": "Archive preview panel title",
    "bead.generating.cancel": "Bead generating cancel",
    "bead.generating.log": "Bead generating log",
    "bead.generating.subtitle": "Bead generating subtitle",
    "bead.pattern.parametersOverline": "Bead pattern parameters overline",
    "bead.pattern.parametersTitle": "Bead pattern parameters title",
    "bead.phase.locked": "Bead phase locked",
    "bead.result.a4Desc": "Bead result a4 desc",
    "bead.result.a4Title": "Bead result a4 title",
    "bead.result.keepTitle": "Bead result keep title",
    "bead.result.overline": "Bead result overline",
    "bead.result.saveHdDesc": "Bead result save hd desc",
    "bead.result.shareDesc": "Bead result share desc",
    "bead.result.shareTitle": "Bead result share title",
    "bead.step.done": "Bead step done",
    "bead.step.inProgress": "Bead step in progress",
    "bead.step.waiting": "Bead step waiting",
    "bell.confirm.body.new": "Bell confirm body new",
    "bell.confirm.body.stale": "Bell confirm body stale",
    "bell.confirm.cancel": "Bell confirm cancel",
    "bell.confirm.confirm": "Bell confirm confirm",
    "bell.confirm.title.new": "Bell confirm title new",
    "bell.confirm.title.stale": "Bell confirm title stale",
    "bell.menu.memories": "Bell menu memories",
    "bell.menu.newPhoto": "Bell menu new photo",
    "bell.menu.title": "Bell menu title",
    "businessCard.template.binding": "Business card template binding",
    "businessCard.template.darkroom": "Business card template darkroom",
    "businessCard.template.gallery": "Business card template gallery",
    "businessCard.template.museum": "Business card template museum",
    "businesscard.loadFailed": "Businesscard load failed",
    "businesscard.selectTemplate": "Businesscard select template",
    "businesscard.spec": "Businesscard spec",
    "businesscard.tag.aloof": "Businesscard tag aloof",
    "businesscard.tag.chatty": "Businesscard tag chatty",
    "businesscard.tag.clingy": "Businesscard tag clingy",
    "businesscard.tag.curious": "Businesscard tag curious",
    "businesscard.tag.foodie": "Businesscard tag foodie",
    "businesscard.tag.gentle": "Businesscard tag gentle",
    "businesscard.tag.lively": "Businesscard tag lively",
    "businesscard.tag.mischievous": "Businesscard tag mischievous",
    "businesscard.tag.sensible": "Businesscard tag sensible",
    "businesscard.tag.sleepy": "Businesscard tag sleepy",
    "businesscard.tag.timid": "Businesscard tag timid",
    "businesscard.tag.tsundere": "Businesscard tag tsundere",
    "common.confirm": "Common confirm",
    "create.bead.abstraction": "Create bead abstraction",
    "create.bead.adjust": "Create bead adjust",
    "create.bead.advanced": "Create bead advanced",
    "create.bead.boardSize": "Create bead board size",
    "create.bead.change": "Create bead change",
    "create.bead.collapsed": "Create bead collapsed",
    "create.bead.color": "Create bead color",
    "create.bead.currentRecipe": "Create bead current recipe",
    "create.bead.cutoutOnly": "Create bead cutout only",
    "create.bead.dailyQuota": "Create bead daily quota",
    "create.bead.denoise": "Create bead denoise",
    "create.bead.desc": "Create bead desc",
    "create.bead.expanded": "Create bead expanded",
    "create.bead.export.desc": "Create bead export desc",
    "create.bead.export.title": "Create bead export title",
    "create.bead.exporting": "Create bead exporting",
    "create.bead.generatePattern": "Create bead generate pattern",
    "create.bead.localProcessHint": "Create bead local process hint",
    "create.bead.materialList": "Create bead material list",
    "create.bead.mode.color": "Create bead mode color",
    "create.bead.mode.letter": "Create bead mode letter",
    "create.bead.outline": "Create bead outline",
    "create.bead.saveAlbum": "Create bead save album",
    "create.bead.saveHd": "Create bead save hd",
    "create.bead.selectEffect": "Create bead select effect",
    "create.bead.source": "Create bead source",
    "create.bead.sourceMeta": "Create bead source meta",
    "create.bead.studio": "Create bead studio",
    "create.bead.transition": "Create bead transition",
    "create.bead.unlimited": "Create bead unlimited",
    "create.bead.viewAll": "Create bead view all",
    "create.bead.viewExport": "Create bead view export",
    "create.bead.zoomHint": "Create bead zoom hint",
    "create.businessCard.desc": "Create business card desc",
    "create.businessCard.title": "Create business card title",
    "create.empty.body": "Create empty body",
    "create.empty.cta": "Create empty cta",
    "create.empty.title": "Create empty title",
    "create.encode.failed": "Create encode failed",
    "create.growthCompare.desc": "Create growth compare desc",
    "create.growthCompare.hint": "Create growth compare hint",
    "create.growthCompare.title": "Create growth compare title",
    "create.header.subtitle": "Create subtitle",
    "create.headline": "Create headline",
    "create.load.failed": "Create load failed",
    "create.petCard.desc": "Digital archive for your pal",
    "create.petCard.hint": "Create pal card hint",
    "create.petCard.selectPhoto": "Create pal card select photo",
    "create.petCard.title": "Pal Profile",
    "create.project.bead.desc": "Create project bead desc",
    "create.project.businessCard.desc": "Create project business card desc",
    "create.project.growthCompare.desc": "Create project growth compare desc",
    "create.project.petCard.desc": "Digital archive for your pal",
    "create.project.redPacket.desc": "Create project red packet desc",
    "create.redPacket.badge": "Create red packet",
    "create.redPacket.desc": "Create red packet desc",
    "create.redPacket.title": "Create red packet title",
    "create.redPacket.wechat": "Create red packet wechat",
    "create.render.failed": "Create render failed",
    "create.save.failed": "Create save failed",
    "create.sectionSupporting": "Create section supporting",
    "create.sectionTitle": "Create section title",
    "create.subheadline": "Create subheadline",
    "decoration.group.daily": "Decoration group daily",
    "decoration.group.film": "Decoration group film",
    "decoration.group.holiday": "Decoration group holiday",
    "decoration.group.memorial": "Decoration group memorial",
    "decoration.group.paper": "Decoration group paper",
    "decoration.group.paw": "Decoration group paw",
    "decoration.group.recommended": "Decoration group recommended",
    "decoration.panel.empty": "Decoration panel empty",
    "editor.adjust.manual": "Editor adjust manual",
    "editor.crop.ratio.free": "Editor crop ratio free",
    "editor.cutout.action.applied": "Edit",
    "editor.cutout.action.error": "Edit",
    "editor.cutout.action.idle": "Edit",
    "editor.cutout.action.processing": "Edit",
    "editor.cutout.done": "Editor cutout done",
    "editor.cutout.localProcessing": "Editor cutout local processing",
    "editor.cutout.notUploaded": "Editor cutout not uploaded",
    "editor.cutout.outputFormat": "Editor cutout output format",
    "editor.cutout.transparentPng": "Editor cutout transparent png",
    "editor.error.title": "Editor error title",
    "editor.exit.dialog.saveTitle": "Editor exit dialog save title",
    "editor.exit.dialog.unsavedTitle": "Editor exit dialog unsaved title",
    "editor.exit.saveAndQuit": "Editor exit save and quit",
    "editor.exit.saveOnly": "Editor exit save only",
    "editor.filter.cool": "Editor filter cool",
    "editor.filter.mono": "Editor filter mono",
    "editor.filter.original": "Editor filter original",
    "editor.filter.soft": "Editor filter soft",
    "editor.panel.adjust": "Editor panel adjust",
    "editor.panel.crop": "Editor panel crop",
    "editor.panel.cutout": "Editor panel cutout",
    "editor.panel.flip": "Editor panel flip",
    "editor.panel.frame": "Editor panel frame",
    "editor.panel.rotate": "Editor panel rotate",
    "editor.panel.sticker": "Editor panel sticker",
    "editor.panel.text": "Editor panel text",
    "editor.text.stroke": "Editor text stroke",
    "editor.tool.frame": "Editor tool frame",
    "editor.tool.sticker": "Editor tool sticker",
    "editor.tool.text": "Editor tool text",
    "editor.transform.ccw": "Editor transform ccw",
    "editor.transform.cw": "Editor transform cw",
    "editor.transform.flipH": "Editor transform flip h",
    "editor.transform.flipV": "Editor transform flip v",
    "field.annotation.label": "Annotation label",
    "field.annotation.placeholder": "Annotation placeholder",
    "field.edit": "Edit",
    "field.owner": "Owner",
    "field.owner.placeholder.fallback": "Owner placeholder fallback",
    "field.tagline": "Tagline",
    "field.tagline.placeholder": "Tagline placeholder",
    "field.tags": "Tags",
    "field.tags.placeholder": "Tags placeholder",
    "gallery.empty.filtered": "Gallery empty filtered",
    "gallery.import.freeArchiveMark": "Gallery import free archive mark",
    "gallery.import.lifeLogMark": "Gallery import life log mark",
    "gallery.import.localMark": "Gallery import local mark",
    "gallery.quota.resilienceMark": "Gallery quota resilience mark",
    "gallery.scan.completeTitle": "Gallery scan complete title",
    "gallery.scan.failedTitle": "Gallery scan failed title",
    "gallery.scan.openSettings": "Gallery scan open settings",
    "gallery.scanImport": "Gallery scan import",
    "gallery.select": "Gallery select",
    "home.backup.banner.action": "Home backup banner",
    "home.editorialTitle": "Home editorial title",
    "home.hero.title": "Home hero title",
    "home.hero.todayLabel": "Home hero today label",
    "home.memoryOpen": "Home memory open",
    "home.memoryTitle": "Home memory title",
    "home.retry": "Home retry",
    "home.today": "Home today",
    "home.upcoming.adoption %@": "Home upcoming adoption %@",
    "home.upcoming.lookBack": "Home upcoming look back",
    "home.upcoming.sectionLabel": "Home upcoming section label",
    "home.yearlyRecap.body": "Home yearly recap body",
    "home.yearlyRecap.title": "Home yearly recap title",
    "memory.addMore": "Memory add more",
    "memory.archiveHint": "Memory archive hint",
    "memory.bodyLabel": "Memory body label",
    "memory.draft": "Memory draft",
    "memory.kind.adoptionDay": "Memory kind adoption day",
    "memory.kind.birthday": "Memory kind birthday",
    "memory.kind.growthCompare": "Memory kind growth compare",
    "memory.kind.milestone": "Memory kind milestone",
    "memory.kind.monthlyRecap": "Memory kind monthly recap",
    "memory.kind.yearlyRecap": "Memory kind yearly recap",
    "memory.occurredAt": "Memory occurred at",
    "memory.photoEvidence": "Memory photo evidence",
    "memory.titleLabel": "Memory title label",
    "memory.type.date": "Memory type date",
    "memory.type.photo": "Memory type photo",
    "memory.type.text": "Memory type text",
    "memory.type.work": "Memory type work",
    "memory.typeLabel": "Memory type label",
    "notify.anniversary.adoption.body %@": "Notify anniversary adoption body %@",
    "notify.memory.title": "Notify memory title",
    "notify.newPhoto.body.new": "Notify new photo body new",
    "notify.newPhoto.body.stale": "Notify new photo body stale",
    "notify.newPhoto.title": "Notify new photo title",
    "paywall.benefit1.desc": "Paywall benefit1 desc",
    "paywall.benefit1.title": "Paywall benefit1 title",
    "paywall.benefit2.desc": "Paywall benefit2 desc",
    "paywall.benefit2.title": "Paywall benefit2 title",
    "paywall.benefit3.desc": "Paywall benefit3 desc",
    "paywall.benefit3.title": "Paywall benefit3 title",
    "paywall.cta.confirm": "Paywall cta confirm",
    "paywall.footer.links": "Paywall links",
    "paywall.hero.features": "Paywall hero features",
    "paywall.hero.subtitle": "Paywall hero subtitle",
    "paywall.hero.title": "Paywall hero title",
    "paywall.plan.annual": "Paywall plan annual",
    "paywall.plan.getApp": "Paywall plan get app",
    "paywall.plan.monthly": "Paywall plan monthly",
    "paywall.purchase.title": "Paywall purchase title",
    "paywall.source": "Paywall source",
    "pet.edit.feature.register": "Pal edit feature register",
    "pet.edit.feature.registered": "Pal edit feature registered",
    "pet.edit.feature.reregister": "Pal edit feature reregister",
    "pet.edit.feature.start": "Pal edit feature start",
    "pet.edit.feature.unavailable": "Pal edit feature unavailable",
    "pet.edit.name.unnamed": "Pal edit name unnamed",
    "pet.edit.notLoaded": "Pal edit not loaded",
    "pet.edit.note.placeholder": "Pal edit note placeholder",
    "pet.edit.saveFailed": "Pal edit save failed",
    "pet.edit.section.avatar": "Pal edit avatar",
    "pet.edit.section.dates": "Pal edit dates",
    "pet.edit.section.feature": "Pal edit feature",
    "pet.edit.section.notes": "Pal edit notes",
    "pet.edit.section.speciesGender": "Pal edit species gender",
    "pet.edit.unsaved.continue": "Pal edit unsaved continue",
    "pet.edit.unsaved.discard": "Pal edit unsaved discard",
    "pet.edit.unsaved.title": "Pal Profile",
    "pet.profile.addMemory": "Pal profile add memory",
    "pet.profile.archiveOrigin": "Pal profile archive origin",
    "pet.profile.born": "Pal profile born",
    "pet.profile.continueRecording": "Pal profile continue recording",
    "pet.profile.continuity.body": "Pal profile continuity body",
    "pet.profile.continuity.headline": "Pal profile continuity headline",
    "pet.profile.edit": "Pal profile edit",
    "pet.profile.importantEvents": "Pal profile important events",
    "pet.profile.intro": "Pal profile intro",
    "pet.profile.nextLeafMark": "Pal profile next leaf mark",
    "pet.profile.noCategoryPhotos": "Pal profile no category photos",
    "pet.profile.noPhotos": "Pal profile no photos",
    "pet.profile.pinned.recent": "Pal profile pinned recent",
    "pet.profile.recentPhotos": "Pal profile recent photos",
    "pet.profile.stat.importantDays": "Pal profile stat important days",
    "pet.profile.timeline.openFull": "Pal profile timeline open full",
    "pet.profile.timeline.sampleBody": "Pal profile timeline sample body",
    "pet.profile.timeline.sampleTitle": "Pal Profile",
    "pet.profile.timelineLink": "Pal profile timeline link",
    "pet.profile.unassignedHint": "Pal profile unassigned hint",
    "pet.profile.unassignedHintBody": "Pal profile unassigned hint body",
    "pet.profile.worksHintBody": "Pal profile works hint body",
    "petcard.gallery.label": "Petcard gallery label",
    "petcard.museum.label": "Petcard museum label",
    "petcard.spec": "Petcard spec",
    "pets.delete": "Pal delete",
    "pets.empty.body": "Pal empty body",
    "photo.assign.empty": "Photo assign empty",
    "photo.assign.failed": "Photo assign failed",
    "photo.assign.title": "Photo assign title",
    "photo.assign.unassign": "Photo assign unassign",
    "photo.assign.unassignHint": "Photo assign unassign hint",
    "photo.batch.assign": "Photo batch assign",
    "photo.bead.create": "Photo bead create",
    "photo.delete.confirmSingle": "Photo delete confirm single",
    "photo.detail.addToMemory": "Photo detail add to memory",
    "photo.detail.archived": "Photo detail archived",
    "photo.detail.assign": "Photo detail assign",
    "photo.detail.editInfo": "Photo detail edit info",
    "photo.detail.share": "Photo detail share",
    "photo.favorite": "Photo favorite",
    "photo.remove.message": "Photo remove message",
    "photo.remove.title": "Photo remove title",
    "photo.unfavorite": "Photo unfavorite",
    "picker.bead.empty": "Picker bead empty",
    "picker.bead.emptyDesc": "Picker bead empty desc",
    "picker.bead.fromArchive": "Picker bead from archive",
    "picker.bead.title": "Picker bead title",
    "picker.businessCard.empty": "Picker business card empty",
    "picker.businessCard.emptyDesc": "Picker business card empty desc",
    "picker.businessCard.fromArchive": "Picker business card from archive",
    "picker.businessCard.title": "Picker business card title",
    "picker.compare.clear": "Picker compare clear",
    "picker.compare.empty": "Picker compare empty",
    "picker.compare.emptyDesc": "Picker compare empty desc",
    "picker.compare.fromArchive": "Picker compare from archive",
    "picker.compare.headline": "Picker compare headline",
    "picker.compare.hint": "Picker compare hint",
    "picker.compare.start": "Picker compare start",
    "picker.compare.title": "Picker compare title",
    "picker.petCard.empty": "Picker pal card empty",
    "picker.petCard.emptyDesc": "Digital archive for your pal",
    "picker.petCard.fromArchive": "Picker pal card from archive",
    "picker.petCard.title": "Pal Profile",
    "picker.redPacket.empty": "Picker red packet empty",
    "picker.redPacket.emptyDesc": "Picker red packet empty desc",
    "picker.redPacket.fromArchive": "Picker red packet from archive",
    "picker.role.earlier": "Picker role earlier",
    "picker.role.recent": "Picker role recent",
    "preview.contentArea": "Preview content area",
    "privacy.commit.gdpr": "Privacy commit gdpr",
    "privacy.commit.gdpr.detail": "Privacy commit gdpr detail",
    "recap.empty.body": "Recap empty body",
    "recap.exportFailed": "Recap export failed"
}
