# -*- coding: utf-8 -*-
"""English translation dictionary - Part 5A (RedPacket, Create, Bead, Pals - 302 keys)."""

P5A_EN = {
    # === RedPacket Workshop (172) ===
    "redpacket.quality.clarity.resolution.detail": "Original photo resolution is high enough to produce a clear cover",
    "redpacket.quality.clarity.soft.detail": "Subject is slightly soft — consider using a sharper photo",
    "redpacket.quality.clarity.unavailable.detail": "Unable to assess image clarity",
    "redpacket.quality.completed": "Quality check completed",
    "redpacket.quality.composition.clipped.detail": "Subject is clipped near the edges — adjust crop inside safe zone",
    "redpacket.quality.composition.pass.detail": "Subject is well centered within the WeChat safe area",
    "redpacket.quality.composition.safezone.detail": "Subject is near edge — keep subject inside safe area",
    "redpacket.quality.composition.small.detail": "Subject is slightly small — zoom in for better presence",
    "redpacket.quality.cutout.background.detail": "Background contains complex elements that may distract from subject",
    "redpacket.quality.cutout.fragmented.detail": "Cutout edges are fragmented — manual refinement recommended",
    "redpacket.quality.cutout.incomplete.detail": "Subject cutout is incomplete — retry auto cutout or refine manually",
    "redpacket.quality.cutout.pass.detail": "Pal subject cutout is clean and smooth",
    "redpacket.quality.cutout.retry.detail": "Cutout failed — try re-selecting subject",
    "redpacket.quality.cutout.rough.detail": "Cutout edges are rough — soften edges in editor",
    "redpacket.quality.cutout.unavailable.detail": "Cutout quality check unavailable",
    "redpacket.quality.dim.brightness": "Brightness & Lighting",
    "redpacket.quality.dim.clarity": "Subject Clarity",
    "redpacket.quality.dim.composition": "Safe Zone Composition",
    "redpacket.quality.dim.cutout": "Cutout Precision",
    "redpacket.quality.dim.readability": "Text Legibility",
    "redpacket.quality.done": "Done",
    "redpacket.quality.hasIssues": "Some items need attention",
    "redpacket.quality.intelligentCheck": "AI Quality Diagnostic",
    "redpacket.quality.level.pass": "Passed Specification",
    "redpacket.quality.notEvaluated": "Not Evaluated",
    "redpacket.quality.onlySuggestion": "Suggestions are for reference only",
    "redpacket.quality.readability.contrast.detail": "Text contrast is low — adjust text color or background brightness",
    "redpacket.quality.readability.noText.detail": "No custom text added",
    "redpacket.quality.readability.pass.detail": "Blessing text is clear and easy to read",
    "redpacket.quality.readability.zone.detail": "Text is positioned within the recommended message area",
    "redpacket.quality.recheck": "Re-check Quality",
    "redpacket.quality.startCheck": "Start Quality Diagnostic",
    "redpacket.quality.status.error": "Issue Found",
    "redpacket.quality.status.pass": "Passed",
    "redpacket.quality.status.warning": "Notice",
    "redpacket.quality.thisAdjustment": "Adjustment Guide",
    "redpacket.render.failed": "Failed to render cover preview",
    "redpacket.save.failed": "Failed to save cover to Photos",
    "redpacket.spec": "957 × 1278 px PNG (< 500 KB)",
    "redpacket.style.elegant": "Graceful Elegance",
    "redpacket.style.petName": "Pal's Blessing",
    "redpacket.style.seal": "Traditional Seal",
    "redpacket.template.floralSpring.desc": "Spring blossoms and warm pastel tones",
    "redpacket.template.floralSpring.title": "Spring Floral",
    "redpacket.template.fortuneGold.desc": "Gold accents symbolizing luck and fortune",
    "redpacket.template.fortuneGold.title": "Golden Fortune",
    "redpacket.template.free": "Free Template",
    "redpacket.template.newYearRed.desc": "Classic auspicious red celebration",
    "redpacket.template.newYearRed.title": "Festive Red",
    "redpacket.template.petFresh.desc": "Clean, refreshing style spotlighting your pal",
    "redpacket.template.petFresh.title": "Pal Fresh",
    "redpacket.title": "Red Packet Covers",
    "redpacket.uploadGuide.link": "Visit WeChat Red Packet Cover Platform",
    "redpacket.uploadGuide.note": "Exported PNG images meet official WeChat submission requirements.",
    "redpacket.watermarkHint": "Free exports include watermark · Pro removes watermark",
    "redpacket.workshop.center": "Center Subject",
    "redpacket.workshop.channel.accessory": "Stickers & Accessories",
    "redpacket.workshop.channel.blessing": "Blessing & Text",
    "redpacket.workshop.channel.pet": "Pal Subject",
    "redpacket.workshop.chooseTemplate": "Select Template",
    "redpacket.workshop.cutoutHint": "Auto-isolate pal subject with one tap",
    "redpacket.workshop.delete": "Delete Layer",
    "redpacket.workshop.enter": "Enter Workshop",
    "redpacket.workshop.export": "Export Cover PNG",
    "redpacket.workshop.layer.accessory": "Accessory Layer",
    "redpacket.workshop.layer.blessing": "Text Layer",
    "redpacket.workshop.layer.pet": "Pal Layer",
    "redpacket.workshop.loadError.back": "Return",
    "redpacket.workshop.loadError.photo": "Failed to load photo",
    "redpacket.workshop.loadError.template": "Failed to load template",
    "redpacket.workshop.noPhotos": "No Photos Available",
    "redpacket.workshop.noPhotosDesc": "Import photos of your pal first to make a custom cover",
    "redpacket.workshop.photoPicker": "Choose Photo",
    "redpacket.workshop.reset": "Reset",
    "redpacket.workshop.selectPhoto": "Select Photo",
    "redpacket.workshop.templatePicker": "Template Gallery",
    "redpacket.workshop.templateSwitcher": "Switch Template",
    "redpacket.workshop.textStyle": "Text Formatting",
    "redpacket.workshop.tool.accessory": "Stickers",
    "redpacket.workshop.tool.optimize": "Diagnose",
    "redpacket.workshop.tool.photo": "Subject",
    "redpacket.workshop.tool.template": "Templates",
    "redpacket.workshop.tool.text": "Blessing",
    "redpacket.workshop.transform.center": "Center",
    "redpacket.workshop.transform.changePhoto": "Change Photo",
    "redpacket.workshop.transform.move": "Move",
    "redpacket.workshop.transform.rotate": "Rotate",
    "redpacket.workshop.transform.scale": "Scale",

    # === Create & Bead Studio (79) ===
    "create.bead.preview.zoomHint": "Pinch to zoom into beads",
    "create.bead.regenerate": "Regenerate",
    "create.card.aspectRatio": "Card Aspect Ratio",
    "create.card.background": "Card Background",
    "create.card.color": "Theme Color",
    "create.card.compact": "Compact Mode",
    "create.card.elements": "Card Elements",
    "create.card.font": "Card Font",
    "create.card.format": "Format",
    "create.card.layout": "Layout Style",
    "create.card.qr": "Add Profile QR Code",
    "create.card.save": "Save Card",
    "create.card.selectPet": "Select Pal",
    "create.card.share": "Share Card",
    "create.card.standard": "Standard Card",
    "create.card.stats": "Show Stats",
    "create.card.style.cute": "Playful",
    "create.card.style.elegant": "Elegant",
    "create.card.style.minimal": "Minimalist",
    "create.card.style.retro": "Vintage",
    "create.card.title.edit": "Edit Pal Card",
    "create.card.title.make": "Make Pal Card",
    "create.card.watermark": "Watermark",
    "create.entry.bead": "Bead Studio",
    "create.entry.card": "Pal Card",
    "create.entry.redpacket": "Red Packet Cover",
    "create.entry.timeline": "Timeline Poster",
    "create.export.failed": "Export Failed",
    "create.export.saving": "Saving image...",
    "create.export.success": "Saved to Photos",
    "create.filter.all": "All Styles",
    "create.filter.popular": "Popular",
    "create.filter.recent": "Recently Used",
    "create.hub.beadDesc": "Turn photos of your pal into pixel bead patterns",
    "create.hub.beadTitle": "Bead Pattern Studio",
    "create.hub.cardDesc": "Personalized digital ID cards for your pal",
    "create.hub.cardTitle": "Pal ID Card",
    "create.hub.redpacketDesc": "Official 957×1278 WeChat red packet covers",
    "create.hub.redpacketTitle": "Red Packet Cover",
    "create.hub.timelineDesc": "Long chronological growth keepsake poster",
    "create.hub.timelineTitle": "Growth Timeline",
    "create.hub.title": "Creative Studio",
    "create.loading.model": "Loading AI model on device...",
    "create.loading.photo": "Preparing photo...",
    "create.palette.brand": "Color Brand",
    "create.palette.customColors": "Custom Colors",
    "create.palette.mardStandard": "MARD Standard (108 Colors)",
    "create.palette.perlerStandard": "Perler Standard",
    "create.pattern.gridToggle": "Grid Lines",
    "create.pattern.numberToggle": "Color Codes",
    "create.pattern.pegboard": "Pegboard View",
    "create.pattern.print": "Print Pattern",
    "create.pattern.savePdf": "Save PDF",
    "create.pattern.sizeLabel": "Dimensions",
    "create.pro.badge": "Pro Feature",
    "create.pro.unlimited": "Unlimited with Pro",
    "create.recent.empty": "No recent creations",
    "create.recent.title": "Recent Creations",
    "create.studio.badge": "Darkroom",
    "create.studio.createKeepsake": "Create Keepsake",
    "create.studio.explore": "Explore Creation Tools",
    "create.studio.heading": "Turn Memories into Art",
    "create.style.beadArt": "Pixel Bead Art",
    "create.template.all": "All Templates",
    "create.template.badge.hot": "HOT",
    "create.template.badge.new": "NEW",
    "create.template.badge.pro": "PRO",
    "create.template.select": "Select Template",
    "create.timeline.config": "Poster Config",
    "create.timeline.dateRange": "Time Range",
    "create.timeline.density": "Photo Density",
    "create.timeline.orientation": "Poster Orientation",
    "create.timeline.palSelect": "Select Pal",
    "create.timeline.style": "Poster Theme",
    "create.timeline.theme.dark": "Midnight Dark",
    "create.timeline.theme.light": "Warm White",
    "create.timeline.theme.vintage": "Vintage Sepia",
    "bead.result.boardCount": "Pegboards",
    "bead.result.colorCount": "Colors",
    "bead.result.totalBeads": "Total Beads",

    # === Pals, Pet Profiles & Cards (51) ===
    "pet.edit.dates.hint": "Birthdays and adoption anniversaries will appear on your timeline and widgets.",
    "pet.edit.dates.title": "Important Dates",
    "pet.edit.deleteConfirmBody %@": "Are you sure you want to delete %@'s profile? Original photos in your library will not be deleted.",
    "pet.edit.deleteConfirmTitle": "Delete Pal Profile",
    "pet.edit.feature.intro": "Visual feature baseline enables local recognition of your pal across photos.",
    "pet.edit.feature.qualityDesc": "Include clear shots from different angles with good lighting.",
    "pet.edit.feature.statusRegistered %lld": "%lld baseline photos registered",
    "pet.edit.feature.statusUnregistered": "No features registered yet",
    "pet.edit.feature.updatePhotos": "Update Baseline Photos",
    "pet.edit.info.footer": "Basic info helps generate customized cards and timeline chapters.",
    "pet.edit.profile.title": "Edit Pal Profile",
    "pet.form.avatar.desc": "Choose a clear photo for your pal's circular avatar",
    "pet.form.avatar.title": "Pal Avatar",
    "pet.form.birthday.desc": "Used to calculate age and birthday reminders",
    "pet.form.birthday.title": "Birthday",
    "pet.form.gender.desc": "Used on pal cards and greetings",
    "pet.form.gender.title": "Gender",
    "pet.form.name.desc": "Enter the name you call your pal",
    "pet.form.name.title": "Pal Name",
    "pet.form.species.desc": "Choose dog, cat, or other",
    "pet.form.species.title": "Species",
    "pet.manage.addPal": "Add Another Pal",
    "pet.manage.currentCount %lld %lld": "%1$lld / %2$lld Pals",
    "pet.manage.delete": "Delete Profile",
    "pet.manage.edit": "Edit Profile",
    "pet.manage.empty": "No pal profiles created",
    "pet.manage.proLimitHint": "Upgrade to Pro to manage up to 20 pal profiles",
    "pet.manage.reorder": "Reorder Pals",
    "pet.manage.title": "Manage Pals",
    "pet.profile.action.addPhotos": "Add Photos",
    "pet.profile.action.deleteProfile": "Delete Profile",
    "pet.profile.action.exportCard": "Export Pal Card",
    "pet.profile.action.scanLibrary": "Scan Library",
    "pet.profile.action.viewAllPhotos": "View All Photos",
    "pet.profile.action.viewTimeline": "View Growth Timeline",
    "pet.profile.card.viewDetails": "View Details",
    "pet.profile.coverPhoto": "Cover Photo",
    "pet.profile.dates.adoption": "Adoption Day",
    "pet.profile.dates.birthday": "Birthday",
    "pet.profile.dates.memorial": "Anniversary",
    "pet.profile.daysTogetherCount %lld": "%lld Days Together",
    "pet.profile.growth.milestones": "Growth Milestones",
    "pet.profile.growth.title": "Growth Journey",
    "pet.profile.stats.memoriesCount %lld": "%lld Memories",
    "pet.profile.stats.photosCount %lld": "%lld Photos",
    "pet.profile.stats.worksCount %lld": "%lld Artworks",
    "petcard.action.flip": "Flip Card",
    "petcard.action.save": "Save Card",
    "petcard.action.share": "Share Card",
    "petcard.back.title": "Pal Passport",
    "petcard.front.title": "Pal Identity Card",
    "pets.empty.createCTA": "Create Pal Profile",
    "pets.empty.description": "Add a profile to start organizing your pal's memories, photos, and milestones.",
}
