# -*- coding: utf-8 -*-
"""English translation dictionary - Part 3 (M09 - M12)."""

# M09: Timeline, Home, Memories & Notify (143)
TIMELINE_HOME_EN = {
    "bell.anniversary.title": "Anniversaries",
    "bell.empty.subtitle": "Important dates with your pal will appear here",
    "bell.empty.title": "No Reminders",
    "bell.list.title": "Reminders",
    "bell.notifications.manage": "Manage Notifications",
    "bell.tab.anniversary": "Anniversaries",
    "bell.tab.timeMachine": "Time Machine",
    "bell.timeMachine.title": "Time Machine Flashback",
    "bell.title": "Memorial Bell",
    "home.action.addPal": "Add a Pal",
    "home.action.allPhotos": "All Photos",
    "home.action.createPattern": "Create Bead Pattern",
    "home.action.scan": "Scan Library",
    "home.backup.banner.cta": "Backup Now",
    "home.backup.banner.message": "It's been a while since your last backup. Back up your pal's memories to keep them safe.",
    "home.backup.banner.title": "Backup Reminder",
    "home.empty.body": "Create a profile for your pal and import photos to begin",
    "home.empty.cta": "Add a Pal",
    "home.empty.title": "No Pal Memories Yet",
    "home.greeting.afternoon": "Good afternoon",
    "home.greeting.evening": "Good evening",
    "home.greeting.morning": "Good morning",
    "home.greeting.night": "Good night",
    "home.hero.badge.memory": "Memory",
    "home.hero.badge.today": "Today's Pick",
    "home.loadError": "Failed to load home data",
    "home.newPhotos.banner %lld": "Found %lld new photos that may feature your pal",
    "home.newPhotos.cta": "Review",
    "home.pinned.title": "Pinned Memories",
    "home.quick.bead": "Bead Art",
    "home.quick.card": "Pal Card",
    "home.quick.scan": "Scan",
    "home.quick.timeline": "Timeline",
    "home.recent.title": "Recent Moments",
    "home.section.memories": "Past Flashbacks",
    "home.section.pals": "My Pals",
    "home.upcoming.birthday %@": "%@'s Birthday",
    "home.upcoming.daysLeft %lld": "In %lld days",
    "home.upcoming.today": "Today!",
    "memory.card.date %@": "Captured %@",
    "memory.card.pinned": "Pinned",
    "memory.card.share": "Share Memory",
    "memory.empty.subtitle": "Pin your favorite photos to see them here",
    "memory.empty.title": "No Pinned Memories",
    "memory.pinned.add": "Pin Memory",
    "memory.pinned.limit": "You can pin up to 6 memories",
    "memory.pinned.remove": "Unpin",
    "memory.pinned.title": "Pinned Memories",
    "memory.section.all": "All Memories",
    "memory.section.pinned": "Pinned",
    "memory.title": "Pal Memories",
    "notify.anniversary.body %@ %lld": "Today is %@'s special day (%lld days together)",
    "notify.anniversary.title": "Anniversary Memory",
    "notify.anniversary.today %@": "Today's memory: %@",
    "notify.backup.body": "Protect your pal's memories — export a local backup today.",
    "notify.backup.title": "Backup Reminder",
    "notify.defaultPetName": "Little One",
    "notify.kind.adoption %@": "%@'s Adoption Anniversary",
    "notify.kind.birthday %@": "%@'s Birthday",
    "notify.kind.memorial %@": "%@'s Anniversary",
    "recap.annual.title %lld": "%lld Year in Review",
    "recap.empty.subtitle": "Archived photos throughout the year will generate an annual recap",
    "recap.empty.title": "No Annual Recap Yet",
    "recap.monthly.title %@": "%@ Monthly Highlights",
    "recap.share": "Share Recap",
    "recap.title": "Life Review",
    "reminders.add.title": "Add Reminder",
    "reminders.date": "Date",
    "reminders.empty.subtitle": "Add custom memorial dates for your pal",
    "reminders.empty.title": "No Custom Reminders",
    "reminders.name": "Reminder Name",
    "reminders.name.placeholder": "e.g. Vaccination, Birthday",
    "reminders.notificationTime": "Reminder Time",
    "reminders.repeat": "Repeat",
    "reminders.repeat.never": "Never",
    "reminders.repeat.yearly": "Every Year",
    "reminders.save": "Save Reminder",
    "reminders.title": "Reminders",
    "timeline.birthday.subtitle %lld": "Birthday #%lld",
    "timeline.birthday.title %@ %lld": "Happy Birthday, %@! 🎂 (#%lld)",
    "timeline.chapter.adoption": "Welcomed Home",
    "timeline.chapter.firstYear": "First Year Together",
    "timeline.chapter.growth": "Growing Up",
    "timeline.chapter.recent": "Recent Days",
    "timeline.chapter.senior": "Golden Years",
    "timeline.empty.body": "Photos of your pal organized by date will form a growth timeline",
    "timeline.empty.cta": "Import Photos",
    "timeline.empty.title": "No Timeline Records",
    "timeline.export.dateRange %@ %@": "%@ — %@",
    "timeline.export.generating": "Generating timeline poster...",
    "timeline.export.preview": "Timeline Poster Preview",
    "timeline.export.saveSuccess": "Timeline saved to Photos",
    "timeline.export.title": "Export Growth Timeline",
    "timeline.export.watermark": "Made with MiLens · Digital Life Archive for Pals",
    "timeline.exportFailedDetail": "Failed to export timeline image. Please try again.",
    "timeline.filter.all": "All Time",
    "timeline.filter.anniversaries": "Anniversaries",
    "timeline.filter.favorites": "Favorites",
    "timeline.filter.pal %@": "%@ Only",
    "timeline.freeLimit.banner": "Free plan includes past 1 year of timeline history. Pro unlocks full lifetime records.",
    "timeline.freeLimit.cta": "Unlock Full History",
    "timeline.milestone.adoption": "Adoption Day",
    "timeline.milestone.birthday": "Birthday",
    "timeline.milestone.firstPhoto": "First Photo",
    "timeline.milestone.hundredDays": "100 Days Together",
    "timeline.milestone.oneYear": "1 Year Anniversary",
    "timeline.milestone.title": "Milestones",
    "timeline.preview.title": "Timeline Full Preview",
    "timeline.renderFailed": "Failed to render timeline poster",
    "timeline.section.month %@": "%@",
    "timeline.section.year %lld": "%lld",
    "timeline.stats.days %lld": "%lld Days",
    "timeline.stats.memories %lld": "%lld Memories",
    "timeline.stats.photos %lld": "%lld Photos",
    "timeline.title": "Growth Timeline",
}

# M10: Gallery, Album, Picker & Photos (131)
GALLERY_PHOTO_EN = {
    "album.allPhotos": "All Photos",
    "album.cameraRoll": "Recents",
    "album.favorites": "Favorites",
    "album.pals": "Pal Photos",
    "album.screenshots": "Screenshots",
    "album.select.title": "Select Album",
    "album.title": "Albums",
    "album.videos": "Videos",
    "gallery.action.delete": "Delete",
    "gallery.action.deselectAll": "Deselect All",
    "gallery.action.favorite": "Favorite",
    "gallery.action.makeBead": "Make Bead Pattern",
    "gallery.action.makeCard": "Make Pal Card",
    "gallery.action.reassign": "Assign to Pal",
    "gallery.action.selectAll": "Select All",
    "gallery.action.share": "Share",
    "gallery.action.unfavorite": "Unfavorite",
    "gallery.batch.count %lld": "%lld Selected",
    "gallery.batch.deleteConfirm %lld": "Delete %lld photos from MiLens library? Original photos in your system library won't be deleted.",
    "gallery.empty.body": "Scan your library or add photos of your pal to get started",
    "gallery.empty.cta": "Scan for Pal Photos",
    "gallery.empty.title": "No Photos Yet",
    "gallery.filter.all": "All",
    "gallery.filter.clear": "Clear Filter",
    "gallery.filter.favorites": "Favorites Only",
    "gallery.filter.pal": "Filter by Pal",
    "gallery.filter.time": "Time Range",
    "gallery.filter.title": "Filter Photos",
    "gallery.filter.unassigned": "Unassigned",
    "gallery.grid.large": "Large Grid",
    "gallery.grid.medium": "Medium Grid",
    "gallery.grid.small": "Small Grid",
    "gallery.scan.banner.scanning": "Scanning photo library on device...",
    "gallery.scan.button": "Scan Library",
    "gallery.scan.permissionDenied": "Photo library permission is required to discover pal photos.",
    "gallery.scan.prompt": "Find new photos of your pal",
    "gallery.sort.dateAsc": "Oldest First",
    "gallery.sort.dateDesc": "Newest First",
    "gallery.sort.quality": "Highest Quality First",
    "gallery.sort.title": "Sort Order",
    "gallery.title": "Gallery",
    "photo.burst.bestBadge": "BEST",
    "photo.burst.count %lld": "%lld Burst Shots",
    "photo.burst.keepAll": "Keep All",
    "photo.burst.keepBestOnly": "Keep Best Shot Only",
    "photo.burst.title": "Burst Photo Group",
    "photo.delete.confirm.message": "This will remove the photo from MiLens records. The original in your system photo library will not be deleted.",
    "photo.delete.confirm.title": "Delete Photo Record",
    "photo.detail.action.bead": "Bead Pattern",
    "photo.detail.action.card": "Pal Card",
    "photo.detail.action.delete": "Delete",
    "photo.detail.action.edit": "Edit Photo",
    "photo.detail.action.favorite": "Favorite",
    "photo.detail.action.info": "Info",
    "photo.detail.action.redpacket": "Red Packet",
    "photo.detail.action.share": "Share",
    "photo.detail.palBadge %@": "Pal: %@",
    "photo.detail.qualityBadge %lld": "Score: %lld",
    "photo.detail.title": "Photo Detail",
    "photo.duplicate.badge": "Similar",
    "photo.duplicate.count %lld": "%lld Similar Photos",
    "photo.duplicate.groupTitle": "Similar Photo Group",
    "photo.duplicate.keepHighest": "Keep Highest Quality",
    "photo.duplicate.resolve": "Clean Up Similars",
    "photo.metadata.camera": "Camera",
    "photo.metadata.date": "Date Taken",
    "photo.metadata.dimensions": "Dimensions",
    "photo.metadata.fileSize": "File Size",
    "photo.metadata.focalLength": "Focal Length",
    "photo.metadata.iso": "ISO",
    "photo.metadata.lens": "Lens",
    "photo.metadata.location": "Location",
    "photo.metadata.noExif": "No EXIF data",
    "photo.metadata.title": "Photo Metadata",
    "photo.quality.clarity %lld": "Clarity: %lld",
    "photo.quality.composition %lld": "Composition: %lld",
    "photo.quality.contrast %lld": "Lighting: %lld",
    "photo.quality.label.excellent": "Crystal Clear",
    "photo.quality.label.good": "Good Quality",
    "photo.quality.label.low": "Low Quality",
    "photo.quality.score %lld": "Quality Score: %lld",
    "photo.quality.title": "Quality Assessment",
    "photo.reassign.confirm %@": "Assign photo to %@?",
    "photo.reassign.title": "Assign to Pal",
    "picker.confirm.button %lld": "Add %lld Photos",
    "picker.filter.all": "All",
    "picker.filter.pals": "Pals Only",
    "picker.limit.max %lld": "Select up to %lld photos",
    "picker.permission.limited.footer": "You gave MiLens access to selected photos. Tap to manage selection.",
    "picker.permission.limited.manage": "Manage Photo Access",
    "picker.permission.request": "Allow Photo Access",
    "picker.redPacket.fromAlbum": "Choose from Album",
    "picker.redPacket.fromPal": "Choose from Pal Profile",
    "picker.selectedCount %lld": "%lld Selected",
    "picker.title": "Select Photos",
    "source.camera": "Camera",
    "source.import": "Imported",
    "source.scan": "Scanned",
    "source.shared": "Shared",
    "upload.failed": "Import failed. Please try again.",
    "upload.importing %lld": "Importing %lld photos...",
    "upload.preparing": "Preparing photos...",
    "upload.progress %lld %lld": "Importing %lld/%lld",
    "upload.success %lld": "Successfully imported %lld photos",
    "upload.title": "Import Photos",
}

# M11: Editor, Decoration & Share (100)
EDITOR_DECORATION_EN = {
    "businessCard.saveFailed": "Failed to save pal card image",
    "businesscard.overline": "HORIZONTAL NAMECARD",
    "businesscard.saveSuccess": "Pal card saved to Photos",
    "businesscard.style.classic": "Classic Card",
    "businesscard.style.cute": "Cute Stamp",
    "businesscard.style.minimal": "Minimalist",
    "businesscard.style.vintage": "Vintage Seal",
    "businesscard.title": "Pal ID Card",
    "decoration.frame.adoptionRibbon": "Family Ribbon Frame",
    "decoration.frame.classicWood": "Classic Wooden Frame",
    "decoration.frame.goldBorder": "Golden Border",
    "decoration.frame.none": "No Frame",
    "decoration.frame.polaroid": "Polaroid Snapshot",
    "decoration.frame.retroStamp": "Vintage Postage Stamp",
    "decoration.frame.title": "Frames",
    "decoration.group.frames": "Frames",
    "decoration.group.stickers": "Stickers",
    "decoration.group.textStyles": "Text Styles",
    "decoration.sticker.title": "Stickers",
    "decoration.textStyle.calligraphy": "Calligraphy",
    "decoration.textStyle.handwritten": "Handwritten",
    "decoration.textStyle.modern": "Modern Sans",
    "decoration.textStyle.serif": "Editorial Serif",
    "decoration.textStyle.title": "Typography Styles",
    "decoration.textStyle.typewriter": "Typewriter",
    "editor.action.apply": "Apply",
    "editor.action.cancel": "Cancel",
    "editor.action.done": "Done",
    "editor.action.redo": "Redo",
    "editor.action.reset": "Reset",
    "editor.action.undo": "Undo",
    "editor.adjust.brightness": "Exposure",
    "editor.adjust.contrast": "Contrast",
    "editor.adjust.reset": "Reset Color",
    "editor.adjust.saturation": "Saturation",
    "editor.adjust.sharpness": "Sharpness",
    "editor.adjust.title": "Color Adjustment",
    "editor.adjust.warmth": "Warmth",
    "editor.crop.1x1": "1:1 Square",
    "editor.crop.3x4": "3:4 Portrait",
    "editor.crop.4x3": "4:3 Landscape",
    "editor.crop.9x16": "9:16 Story",
    "editor.crop.free": "Freeform",
    "editor.crop.original": "Original Ratio",
    "editor.crop.rotateLeft": "Rotate Left",
    "editor.crop.rotateRight": "Rotate Right",
    "editor.crop.title": "Crop & Rotate",
    "editor.cutout.action.auto": "Auto Cutout",
    "editor.cutout.action.clear": "Clear Cutout",
    "editor.cutout.action.invert": "Invert Mask",
    "editor.cutout.action.manual": "Manual Refine",
    "editor.cutout.failed": "Cutout failed. Try manual selection.",
    "editor.cutout.processing": "Isolating pal subject on device...",
    "editor.cutout.title": "Subject Cutout",
    "editor.filter.bw": "Black & White",
    "editor.filter.film": "Vintage Film",
    "editor.filter.fresh": "Fresh Airy",
    "editor.filter.none": "Original",
    "editor.filter.title": "Filters",
    "editor.filter.vivid": "Vivid Pop",
    "editor.filter.warm": "Warm Sunshine",
    "editor.tab.adjust": "Adjust",
    "editor.tab.crop": "Crop",
    "editor.tab.cutout": "Cutout",
    "editor.tab.decoration": "Decorate",
    "editor.tab.filter": "Filters",
    "editor.tab.text": "Text",
    "editor.text.add": "Add Text",
    "editor.text.align": "Alignment",
    "editor.text.color": "Text Color",
    "editor.text.font": "Font",
    "editor.text.placeholder": "Enter text...",
    "editor.text.size": "Font Size",
    "editor.text.title": "Text Tool",
    "editor.title": "Photo Editor",
    "growthcompare.overline": "GROWTH COMPARE",
    "growthcompare.subtitle": "Compare how your pal grew across dates",
    "growthcompare.title": "Growth Comparison",
    "share.card.title": "Share Pal Card",
    "share.general.title": "Share",
    "share.preview.caption": "Sharing a precious moment with my pal via MiLens",
    "share.preview.more": "More Options",
    "share.preview.overline": "READY TO KEEP",
    "share.preview.platform.instagram": "Instagram",
    "share.preview.platform.photos": "Save to Photos",
    "share.preview.platform.redNote": "RED (Xiaohongshu)",
    "share.preview.platform.system": "System Share",
    "share.preview.platform.wechat": "WeChat",
    "share.preview.saveImage": "Save Image",
    "share.preview.subtitle": "Export with watermark free; upgrade to Pro to remove watermark",
    "share.preview.title": "Share Preview",
    "share.preview.watermarkHint": "Free exports include MiLens watermark · Upgrade to Pro to remove",
}

# M12: A11y, Common, State & Literals (105)
A11Y_LITERALS_EN = {
    "+": "+",
    "·": "·",
    "AI 模型未就绪，暂不能注册视觉特征": "AI models aren't ready yet — visual features can't be registered right now.",
    "a11y.editor.color %@": "Color %@",
    "a11y.gallery.date %lld %lld": "%lld/%lld",
    "a11y.home.openPhoto %@": "Open photo %@",
    "a11y.onboarding.step %lld %lld": "Step %lld of %lld",
    "a11y.pets.avatar %@": "%@'s avatar",
    "a11y.timeline.openRecord %@": "Open record %@",
    "action.cancel": "Cancel",
    "action.confirm": "Confirm",
    "archive.title": "Archive",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.delete": "Delete",
    "common.done": "Done",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.ok": "OK",
    "common.retry": "Retry",
    "common.save": "Save",
    "field.adoptionDate": "Adoption Date",
    "field.age": "Age",
    "field.avatar": "Avatar",
    "field.birthday": "Birthday",
    "field.gender": "Gender",
    "field.memo": "Memo",
    "field.name": "Name",
    "field.notes": "Notes",
    "field.species": "Species",
    "field.weight": "Weight",
    "preview.title": "Preview",
    "tab.create": "Create",
    "tab.home": "Home",
    "tab.pets": "Pals",
    "tab.settings": "Me",
    "为它建立一份档案，\n照片、纪念日和故事都会留在这里。": "Create a profile for your pal —\nphotos, anniversaries, and stories all live here.",
    "从相册里选几张和它有关的照片，\n我们会把每一天整理好。": "Pick a few photos of your pal from your library,\nand we'll organize every day for you.",
    "你的照片只属于你": "Your photos belong to you",
    "保存": "Save",
    "先到相册导入照片，再回来生成拼豆图纸": "Import photos from your library first, then come back to create a bead pattern",
    "先留下一张照片": "Add a photo first",
    "原图预览 · 生成后这里会实时显示拼豆效果": "Original preview · the bead effect will appear here after generation",
    "只会从咪Lens 的整理记录中移除，不会删除系统相册原图。": "This only removes it from MiLens' organized records — originals in your system photo library won't be deleted.",
    "头像": "Avatar",
    "将清除 MiLens 中的相册记录、宠物档案及沙盒中已保存的照片副本（导入/编辑产物），且无法恢复。系统相册中的原图不会被删除。": "This clears MiLens' album records, pal profiles, and saved photo copies in the sandbox (imported/edited works). This cannot be undone. Originals in your system photo library won't be deleted.",
    "开始注册": "Start Registering",
    "打开本地相册记录时出现问题。您可以重试，或重建本地数据：清除 MiLens 记录，同时也会删除沙盒中已保存的照片副本（导入/编辑产物）。系统相册中的原图不受影响。": "There was a problem opening your local library. You can retry, or rebuild local data: this clears MiLens' records and also deletes photo copies saved in the sandbox (imported/edited works). Originals in your system photo library are unaffected.",
    "扫描系统相册，自动发现你的宠物照片": "Scan your photo library to automatically find photos of your pal",
    "未标注日期": "No date",
    "本地数据无法加载": "Can't Load Local Data",
    "档案加载失败": "Failed to Load Profile",
    "没有符合条件的照片": "No matching photos",
    "添加伙伴": "Add a Pal",
    "添加宠物档案和照片后，这里会自动生成成长时间线": "After you add a pal profile and photos, a growth timeline will appear here automatically",
    "添加照片": "Add Photos",
    "特别的缘分": "What a special connection",
    "知道啦": "Got it",
    "视觉特征": "Visual Features",
    "还没有伙伴档案": "No pal profiles yet",
    "还没有成长记录": "No growth records yet",
    "还没有照片": "No photos yet",
    "这位可爱的宝贝和本APP的开发者同一天出生。\n感谢屏幕前的你，呵护着如此珍贵的生命。": "This lovely one shares a birthday with the app's developer.\nThank you for caring for such a precious life.",
    "选择照片生成拼豆图纸": "Pick a photo to create a bead pattern",
    "重要事件": "Important Events",
    "随时可以在相册页扫描并导入更多照片": "You can scan and import more photos from the album page anytime",
    "🎂": "🎂",
}
