# -*- coding: utf-8 -*-
"""English translation dictionary - Part 6 (Final 504 keys)."""

FINAL_EN = {
    "recap.monthCount %lld": "%lld memories",
    "recap.monthPhoto %@": "%@ Highlights",
    "recap.renderFailed": "Failed to generate life review",
    "recap.totalPhotos %lld": "%lld total photos archived",
    "recap.exportFailedDetail %@": "Export failed: %@",
    "recovery.diagCreateFailed %@": "Failed to create directory: %@",
    "recovery.diagError %@": "Error: %@",
    "recovery.diagHeader": "MiLens Diagnostics Log",
    "recovery.diagTime %@": "Time: %@",
    "recovery.diagWriteFailed %@": "Failed to write log file: %@",
    "recovery.diagnosticsExported": "Diagnostics log exported",
    "recovery.exportDiagnostics": "Export Diagnostics",
    "recovery.exportFailed": "Diagnostics export failed",
    "recovery.rebuild": "Rebuild",
    "recovery.rebuildConfirmTitle": "Rebuild Local Database",
    "recovery.rebuildData": "Rebuild Database",
    "redpacket.accessory.bow": "Bowknot",
    "redpacket.accessory.coin": "Lucky Coin",
    "redpacket.accessory.firecracker": "Firecrackers",
    "redpacket.accessory.flower": "Flower",
    "redpacket.accessory.heart": "Warm Heart",
    "redpacket.accessory.lantern": "Lantern",
    "redpacket.accessory.paw": "Lucky Paw",
    "redpacket.accessory.star": "Star",
    "redpacket.action.export": "Export Cover",
    "redpacket.action.share": "Share Cover",
    "redpacket.coverTitle": "Cover Title",
    "redpacket.coverTitle.placeholder": "Enter cover title...",
    "redpacket.cutout.canEdit": "Adjust Cutout",
    "redpacket.cutout.changePhoto": "Change Photo",
    "redpacket.cutout.confirmTitle": "Confirm Cutout",
    "redpacket.cutout.continue": "Continue",
    "redpacket.cutout.done": "Cutout Done",
    "redpacket.cutout.failed": "Cutout failed. Please try manual brush.",
    "redpacket.cutout.failedShort": "Cutout Failed",
    "redpacket.cutout.loading": "Processing cutout on device...",
    "redpacket.cutout.nextStep": "Next Step",
    "redpacket.cutout.processing": "Isolating pal subject on device...",
    "redpacket.cutout.ready": "Cutout Ready",
    "redpacket.cutout.retry": "Retry Cutout",
    "redpacket.cutout.status": "Cutout Status",
    "redpacket.cutout.subjectSeparated": "Pal subject separated from background",
    "redpacket.cutout.tool.changePhoto": "Change Photo",
    "redpacket.cutout.tool.cutout": "Cutout",
    "redpacket.cutout.tool.retry": "Retry",
    "redpacket.export.chatPreview": "Chat Bubble Preview",
    "redpacket.export.defaultSender": "Little One's Family",
    "redpacket.export.defaultTitle": "Happy New Year",
    "redpacket.export.discard": "Discard",
    "redpacket.export.editorialTitle": "WeChat Cover",
    "redpacket.export.exceeded": "File size exceeds 500 KB limit",
    "redpacket.export.fail.fileSize": "File size exceeds 500 KB limit",
    "redpacket.export.fail.format": "Must be PNG or JPG format",
    "redpacket.export.fail.size": "Resolution must be exactly 957 × 1278",
    "redpacket.export.fileSize": "File Size: < 500 KB",
    "redpacket.export.hasWatermark": "Watermarked (Free)",
    "redpacket.export.howToUse": "How to Submit to WeChat",
    "redpacket.export.loadFailed": "Failed to prepare export image",
    "redpacket.export.noWatermark": "No Watermark (Pro)",
    "redpacket.export.openButton": "WeChat Open Button Safe Zone",
    "redpacket.export.passed": "All specifications verified",
    "redpacket.export.previewNote": "Multi-scene WeChat preview simulation",
    "redpacket.export.proHint": "Upgrade to Pro for watermark-free covers",
    "redpacket.export.productCheck": "Specifications Check",
    "redpacket.export.saveOrShare": "Save to Photos or Share",
    "redpacket.export.saved": "Saved to Photos",
    "redpacket.export.scene.banner": "Banner View",
    "redpacket.export.scene.card": "Cover Card",
    "redpacket.export.scene.list": "List View",
    "redpacket.export.scene.open": "Envelope View",
    "redpacket.export.sceneLabel": "Scene",
    "redpacket.export.scenePreview": "WeChat Scene Simulation",
    "redpacket.export.shareFailed": "Failed to share cover",
    "redpacket.export.shareReady": "Cover is ready to share",
    "redpacket.export.shareTitle": "Share WeChat Cover",
    "redpacket.export.size": "957 × 1278 px",
    "redpacket.export.status": "Export Status",
    "redpacket.export.step.openCover": "1. Open WeChat Cover Platform",
    "redpacket.export.step.saveImage": "2. Select exported PNG image",
    "redpacket.export.step.selectCustom": "3. Submit for official review",
    "redpacket.optimize.after": "After Optimization",
    "redpacket.optimize.applied": "Optimizations applied",
    "redpacket.optimize.before": "Before Optimization",
    "redpacket.optimize.button": "Auto-Optimize Layout",
    "redpacket.optimize.disclaimer": "Layout auto-adjusted to comply with WeChat safe area guidelines",
    "redpacket.optimize.noSourceChange": "Original photo remains untouched",
    "redpacket.optimize.suggestTitle": "Layout Recommendations",
    "redpacket.optimize.summary.noChanges": "Layout already meets WeChat safe zone guidelines",
    "redpacket.optimize.summary.petPos": "Pal subject repositioned to upper-middle safe area",
    "redpacket.optimize.summary.textPos": "Blessing text moved clear of the WeChat open button",
    "redpacket.optimize.undoThis": "Undo Layout Optimization",
    "redpacket.quality.allGood": "All quality checks passed",
    "redpacket.quality.brightness.bright.detail": "Photo is %lld%% overexposed — consider reducing brightness",
    "redpacket.quality.brightness.dark.detail": "Photo is %lld%% underexposed — consider increasing brightness",
    "redpacket.quality.brightness.highlightClipping.detail": "Highlights clipped by %lld%% — consider lowering exposure",
    "redpacket.quality.brightness.shadowClipping.detail": "Shadow details lost by %lld%% — consider lifting shadows",
    "redpacket.quality.brightness.pass.detail": "Brightness and exposure are well balanced",
    "redpacket.quality.brightness.unavailable.detail": "Unable to evaluate lighting",
    "redpacket.quality.clarity.blur.detail": "Image sharpness Laplacian score is %lld — recommend a clearer photo",
    "redpacket.quality.clarity.pass.detail": "Pal subject has good sharpness and crisp details",
    "home.backup.banner.body %lld": "You have recorded %1$lld moments. Back up now to keep these precious memories safe.",
    "home.hero.date %lld %lld %@": "%1$lld/%2$lld · %3$@",
    "home.memory.datePet %@ %@": "%@ · %@",
    "home.upcoming.days.adoption %lld %lld": "In %lld days · %lld days together",
    "home.upcoming.days.adoption.arrived %lld %lld": "In %lld days · %lld days home",
    "home.upcoming.days.adoption.family %@ %lld %lld": "In %lld days · %@ family for %lld days",
    "home.upcoming.days.adoption.together %lld %lld": "In %lld days · %lld days together",
    "home.upcoming.days.birthday %lld %lld": "In %lld days · %lld years old",
    "home.upcoming.days.memorial %lld %lld": "In %lld days · recorded for %lld days",
    "memory.saveToPet %@": "Save to %@'s Archive",
    "notify.anniversary.adoption.title %@": "Today is %@'s Adoption Anniversary",
    "notify.anniversary.birthday.body %@": "Relive %@'s wonderful memories over the past year.",
    "notify.anniversary.birthday.title %@": "%@'s Birthday Today 🎂",
    "notify.memory.today %@": "Today's memory: %@",
    "notify.milestone.body %@ %lld": "%@ has been with you for %lld days!",
    "notify.milestone.title %lld": "%lld Days Milestone",
    "field.owner.placeholder %@": "e.g. %@'s Human",
    "pet.edit.feature.selected %lld": "%lld selected",
    "pet.edit.feature.success %lld": "Successfully registered %lld baseline photos",
    "pet.edit.note.footer %lld": "Up to %lld characters",
    "pet.edit.note.tooLong %lld": "Notes cannot exceed %lld characters",
    "pet.edit.note.tooLongToSave %lld": "Notes exceed %lld characters — please shorten before saving",
    "pet.profile.viewAll %lld": "View All %lld Photos",
    "pets.card.photoCount %lld": "%lld photos",
    "photo.assign.batchTitle %lld": "Assign %lld Photos",
    "photo.batch.selected %lld": "%lld selected",
    "gallery.photoCount %lld": "%lld photos",
    "gallery.scan.importPhotos %lld": "Import %lld Photos",
    "gallery.scan.progress %@": "Scanning: %@",
    "gallery.scan.noPalSelected": "Please select a pal to scan for",
    "gallery.scan.ready": "Ready to scan",
    "gallery.scan.scanningPhotos": "Scanning photos...",
    "photo.metadata.aperture": "Aperture",
    "photo.metadata.exposure": "Exposure",
    "photo.metadata.make": "Device Maker",
    "photo.metadata.model": "Camera Model",
    "photo.metadata.software": "Software",
    "common.apply": "Apply",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.reset": "Reset",
    "common.select": "Select",
    "common.skip": "Skip",
    "state.empty": "Empty",
    "state.error": "Error",
    "state.loading": "Loading",
    "state.success": "Success"
}
